TOPDIR=../../../..
ifndef SRCDIR
  SRCDIR=.
endif

include $(SRCDIR)/$(TOPDIR)/lib/GlobalMakefile

SUBDIRS = basis intv2 dmtqc dmtsym dmtscf force wfn mpqc mbpt

include $(SRCDIR)/$(TOPDIR)/lib/GlobalSubDirs

