TOPDIR=../../../..
ifndef SRCDIR
  SRCDIR=.
endif

include $(SRCDIR)/$(TOPDIR)/lib/GlobalMakefile

SUBDIRS = intv2 dmtqc dmtsym dmtscf force basis integral wfn mpqc mbpt

include $(SRCDIR)/$(TOPDIR)/lib/GlobalSubDirs

