
concat = 1
overlap = 0
eigvals = 0
state   = 0
so      = 1
atoms   = 1
petite  = 0
gpetite  = 1
values  = 1
extent  = 1
aoorthog = 1

shell = [3 3 3 3]

xmolecule = $:ico_d5

xbasislist = [ "6-31+G*" ]
basislist = [
 "STO-2G"
 "STO-3G"
 "STO-3G*"
 "STO-6G"
 "MINI (Huzinaga)"
 "MINI (Scaled)"
 "MIDI (Huzinaga)"
 "DZ (Dunning)"
 "DZP (Dunning)"
 "DZP + Diffuse (Dunning)"
 "3-21G"
 "3-21G*"
 "3-21++G"
 "3-21++G*"
 "4-31G"
 "6-31G"
 "6-31G*"
 "6-31G**"
 "6-31+G*"
 "6-31++G"
 "6-31++G*"
 "6-31++G**"
 "6-311G"
 "6-311G*"
 "6-311G**"
 "6-311G(2df,2pd)"
 "6-311++G**"
 "6-311++G(2d,2p)"
 "6-311++G(3df,3pd)"
 "cc-pVDZ"
 "cc-pVTZ"
 "cc-pVQZ"
 "cc-pV5Z"
 "cc-pV6Z"
 "aug-cc-pVDZ"
 "aug-cc-pVTZ"
 "aug-cc-pVQZ"
 "aug-cc-pV5Z"
 "aug-cc-pV6Z"
 "cc-pCVDZ"
 "cc-pCVTZ"
 "cc-pCVQZ"
 "cc-pCV5Z"
 "aug-cc-pCVDZ"
 "aug-cc-pCVTZ"
 "aug-cc-pCVQZ"
 "aug-cc-pCV5Z"
 "NASA Ames ANO"
 "pc-0"
 "pc-1"
 "pc-2"
 "pc-3"
 "pc-4"
 "pc-0-aug"
 "pc-1-aug"
 "pc-2-aug"
 "pc-3-aug"
 "pc-4-aug"
 ]

h2o<Molecule>: (
  symmetry = c2v
  { atoms geometry } = {
    o  [ 0.0  0.0  0.0 ]
    h  [ 1.5  0.0  1.0 ]
    }
 )

he<Molecule>: (
  symmetry = c1
  { atoms geometry } = {
    he  [ 0.0  0.0  0.0 ]
    }
 )

h2<Molecule>: (
  symmetry = d2h
  { atoms geometry } = {
    h  [ 0.0  0.0   0.7 ]
    h  [ 0.0  0.0  -0.7 ]
    }
 )

ne<Molecule>: (
  symmetry = c1
  { atoms geometry } = {
    he  [ 0.0  0.0  0.0 ]
    }
 )

molecule = $:h2

test2 : [
 <GaussianBasisSet>: (
   molecule = $:molecule
   %name = "foo"
   name = "STO-3G"
   %name = "6-31G**"
   %name = "aug-cc-pVTZ"
   %puream=yes
 )
]

concat1<GaussianBasisSet>: (
   molecule = $:molecule
   name = "6-31G*"
)

concat2<GaussianBasisSet>: (
   molecule = $:molecule
   name = "cc-pVDZ"
)

concat12<UnionBasisSet>: (
   basis1 = $:concat1
   basis2 = $:concat2
)

test : [
 <GaussianBasisSet>: (
   molecule = $:molecule
   %name = "foo"
   %name = "STO-3G"
   %name = "6-31G*"
   name = "6-311G**"
   %name = "cc-pVDZ"
   %name = "aug-cc-pVDZ"
   %name = "cc-pVTZ"
   %name = "aug-cc-pVTZ"
   %puream=yes
 )
]

xtest: [
 <GaussianBasisSet>: (
   molecule = $:molecule
   name = "STO-3G"
   )

 <GaussianBasisSet>: (
   molecule = $:molecule
   name = "STO-3G"
   {element basis} = {
      C   "STO-2G"
     }
   )
 <GaussianBasisSet>: (
   molecule = $:molecule
   basis = [ "STO-2G"
             "STO-3G"
             "STO-2G"
             "STO-3G"
             "STO-2G"
             ]
   )
 ]


basis: (
  hydrogen: "foo": [
    (type: [am = s]
            {exp               coef:0} = {
       1.307093214e+02   1.0
       }
    )
  ]
  carbon: "foo": [
    (type: [am = d]
            {exp               coef:0} = {
       1.307093214e+02   1.0
       }
    )
  ]
  nitrogen: "foo": [
    (type: [am = s]
            {exp               coef:0} = {
       1.307093214e+02   1.0
       }
    )
  ]
)

ico<Molecule>: (
  symmetry = ih
  angstrom=yes
  { atoms geometry } = {
       C      [     0.0000000000    0.0000000000    1.4000000000 ]
  }
)

ico_d5<Molecule>: (
  symmetry = d5d
  angstrom=yes
  { atoms geometry } = {
       C      [     0.0000000000    0.0000000000    1.4000000000 ]
       C      [     0.0000000000   -1.2521980674    0.6260990337 ]
  }
)

dodec<Molecule>: (
  symmetry = ih
  angstrom = yes
  { atoms geometry } = {
    C        [   1.2762577889    0.0000000000    1.6706431349 ]
  }
)

dodec_d5<Molecule>: (
  symmetry = d5d
  angstrom = yes
  { atoms geometry } = {
    C        [   0.0000000000    1.6300000000    0.3070000000 ]
    C        [   0.0000000000    1.0130000000    1.3130000000 ]
  }
)

bucky<Molecule>: (
  symmetry = ih
  angstrom = yes
  { atoms geometry } = {
       C      [    -1.2265000000    0.0000000000    3.3145000000 ]
  }
)

bucky_d5<Molecule>: (
  symmetry = d5d
  angstrom = yes
  { atoms geometry } = {
       C      [     0.0000000000   -1.2265000000    3.3145000000 ]
       C      [     0.0000000000   -2.4160714497    2.5793044120 ]
       C      [     0.6992125547    2.9469022060    1.8212857248 ]
       C      [     3.4642913133   -0.3675977940    0.5947857248 ]
  }
)

%
% Local Variables:
% mode: keyval
% End:
%
