//
// lambdapenergy.cc
//
// Copyright (C) 2009 Toru Shiozaki
//
// Author: Toru Shiozaki <shiozaki@qtp.ufl.edu>
// Maintainer: TS
//
// This file is part of the SC Toolkit.
//
// The SC Toolkit is free software; you can redistribute it and/or modify
// it under the terms of the GNU Library General Public License as published by
// the Free Software Foundation; either version 2, or (at your option)
// any later version.
//
// The SC Toolkit is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Library General Public License for more details.
//
// You should have received a copy of the GNU Library General Public License
// along with the SC Toolkit; see the file COPYING.LIB.  If not, write to
// the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
//
// The U.S. Government is granted a limited license as per AL 91-7.
//
  
// This is a C++ code generated by SMITH
  
#include <algorithm>
#include <chemistry/qc/ccr12/lambdapenergy.h>
#include <chemistry/qc/ccr12/tensor.h>
using namespace sc;
  
  
LAMBDAPENERGY::LAMBDAPENERGY(CCR12_Info* info):z(info){};
LAMBDAPENERGY::~LAMBDAPENERGY(){};
  
  
  
void LAMBDAPENERGY::compute_amp(Ref<Tensor>& out){ //k_i0_offset,z->bs2(),z->gt2(),z->f1(),z->in.at(0),z->glambda2(),z->ly(),z->t1(),z->t2(),z->v2(),z->vd2()=>z->xs2()
  
in.resize(8);
kn.resize(64);
  
kn.at(0)=new Tensor("lambdapenergy_k0",z->mem());
offset_k0();
smith_k0(); //z->t2(),z->ly()=>kn.at(0)
smith_0_1(out); //z->f1(),kn.at(0)=>out
in.at(1)=new Tensor("lambdapenergy_1_2",z->mem());
offset_smith_0_2();
in.at(2)=new Tensor("lambdapenergy_2_2",z->mem());
offset_smith_1_2();
smith_2_2(); //z->glambda2(),z->xs2()=>in.at(2)
smith_1_2(); //z->gt2(),in.at(2)=>in.at(1)
delete in.at(2);
smith_0_2(out); //z->f1(),in.at(1)=>out
delete in.at(1);
in.at(1)=new Tensor("lambdapenergy_1_3",z->mem());
offset_smith_0_3();
smith_1_3(); //z->glambda2(),z->bs2()=>in.at(1)
smith_0_3(out); //z->gt2(),in.at(1)=>out
delete in.at(1);
in.at(1)=new Tensor("lambdapenergy_1_0",z->mem());
offset_smith_0_4();
smith_0_4_0(); //z->vd2()=>in.at(1)
smith_1_10(); //z->t2(),z->vd2()=>in.at(1)
smith_0_4(out); //z->glambda2(),in.at(1)=>out
delete in.at(1);
in.at(1)=new Tensor("lambdapenergy_1_1",z->mem());
offset_smith_0_5();
in.at(2)=new Tensor("lambdapenergy_2_0",z->mem());
offset_smith_1_5();
smith_1_5_0(); //z->v2()=>in.at(2)
in.at(3)=new Tensor("lambdapenergy_3_0",z->mem());
offset_smith_2_7();
smith_2_7_0(); //z->v2()=>in.at(3)
smith_3_11(); //z->t1(),z->v2()=>in.at(3)
smith_2_7(); //z->t1(),in.at(3)=>in.at(2)
delete in.at(3);
smith_2_14(); //z->t2(),z->v2()=>in.at(2)
smith_1_5(); //z->ly(),in.at(2)=>in.at(1)
delete in.at(2);
smith_1_6(); //z->glambda2(),z->vd2()=>in.at(1)
in.at(2)=new Tensor("lambdapenergy_2_8",z->mem());
offset_smith_1_8();
smith_2_8(); //z->t1(),z->glambda2()=>in.at(2)
smith_1_8(); //z->vd2(),in.at(2)=>in.at(1)
delete in.at(2);
smith_1_12(); //z->v2(),kn.at(0)=>in.at(1)
in.at(2)=new Tensor("lambdapenergy_2_13",z->mem());
offset_smith_1_13();
smith_2_13(); //z->t2(),z->ly()=>in.at(2)
smith_1_13(); //z->v2(),in.at(2)=>in.at(1)
delete in.at(2);
smith_0_5(out); //z->t1(),in.at(1)=>out
delete in.at(1);
in.at(1)=new Tensor("lambdapenergy_1_9",z->mem());
offset_smith_0_9();
smith_1_9(); //z->ly(),z->v2()=>in.at(1)
smith_0_9(out); //z->t2(),in.at(1)=>out
delete in.at(1);
delete kn.at(0);
  
}
  
void LAMBDAPENERGY::offset_k0(){ 
 
long size=0L; 
for (long p4b=z->noab();p4b<z->noab()+z->nvab();++p4b) { 
 for (long q3b=z->noab()+z->nvab();q3b<z->nab();++q3b) { 
  if (z->get_spin(p4b)==z->get_spin(q3b)) { 
   if ((z->get_sym(p4b)^z->get_sym(q3b))==(z->irrep_t()^z->irrep_y())) { 
    if (!z->restricted() || z->get_spin(p4b)+z->get_spin(q3b)!=4L) { 
     kn[0]->input_offset(q3b-z->noab()-z->nvab()+z->ncab()*(p4b-z->noab()),size); 
     size+=z->get_range(p4b)*z->get_range(q3b); 
    } 
   } 
  } 
 } 
} 
kn[0]->set_filesize(size); 
kn[0]->createfile(); 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::smith_0_1(Ref<Tensor>& out){ 
      
long tileoffset; 
if (out->is_this_local(0L)) { 
 if (z->irrep_e()==(z->irrep_f()^z->irrep_v())) { 
  long dimc=1; 
  double* k_c_sort=z->mem()->malloc_local_double(dimc); 
  std::fill(k_c_sort,k_c_sort+(size_t)dimc,0.0); 
  for (long p2b=z->noab();p2b<z->noab()+z->nvab();++p2b) { 
   for (long q1b=z->noab()+z->nvab();q1b<z->nab();++q1b) { 
    if (z->get_spin(q1b)==z->get_spin(p2b)) { 
     if ((z->get_sym(q1b)^z->get_sym(p2b))==z->irrep_f()) { 
      long q1b_0,p2b_0; 
      z->restricted_2(q1b,p2b,q1b_0,p2b_0); 
      long p2b_1,q1b_1; 
      z->restricted_2(p2b,q1b,p2b_1,q1b_1); 
      long dim_common=z->get_range(p2b)*z->get_range(q1b); 
      long dima0_sort=1L; 
      long dima0=dim_common*dima0_sort; 
      long dima1_sort=1L; 
      long dima1=dim_common*dima1_sort; 
      if (dima0>0L && dima1>0L) { 
       double* k_a0_sort=z->mem()->malloc_local_double(dima0); 
       double* k_a0=z->mem()->malloc_local_double(dima0); 
       z->f1()->get_block(p2b_0+(z->nab())*(q1b_0),k_a0); 
       z->sort_indices2(k_a0,k_a0_sort,z->get_range(q1b),z->get_range(p2b),0,1,+1.0,false); 
       z->mem()->free_local_double(k_a0); 
       double* k_a1_sort=z->mem()->malloc_local_double(dima1); 
       double* k_a1=z->mem()->malloc_local_double(dima1); 
       kn[0]->get_block(q1b_1-z->noab()-z->nvab()+z->ncab()*(p2b_1-z->noab()),k_a1); 
       z->sort_indices2(k_a1,k_a1_sort,z->get_range(p2b),z->get_range(q1b),1,0,+1.0,false); 
       z->mem()->free_local_double(k_a1); 
       double factor=1.0; 
       z->smith_dgemm(dima0_sort,dima1_sort,dim_common,factor,k_a0_sort,dim_common,k_a1_sort,dim_common,1.0,k_c_sort,dima0_sort); 
       z->mem()->free_local_double(k_a1_sort); 
       z->mem()->free_local_double(k_a0_sort); 
      } 
     } 
    } 
   } 
  } 
  double* k_c=z->mem()->malloc_local_double(dimc); 
  z->sort_indices0(k_c_sort,k_c,1.0,false); 
  out->add_block((0),k_c); 
  z->mem()->free_local_double(k_c); 
  z->mem()->free_local_double(k_c_sort); 
 } 
} 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::smith_0_2(Ref<Tensor>& out){ 
      
long tileoffset; 
if (out->is_this_local(0L)) { 
 if (z->irrep_e()==(z->irrep_f()^(z->irrep_t()^(z->irrep_y()^z->irrep_e())))) { 
  long dimc=1; 
  double* k_c_sort=z->mem()->malloc_local_double(dimc); 
  std::fill(k_c_sort,k_c_sort+(size_t)dimc,0.0); 
  for (long h1b=0L;h1b<z->noab();++h1b) { 
   for (long h2b=0L;h2b<z->noab();++h2b) { 
    if (z->get_spin(h1b)==z->get_spin(h2b)) { 
     if ((z->get_sym(h1b)^z->get_sym(h2b))==z->irrep_f()) { 
      long h1b_0,h2b_0; 
      z->restricted_2(h1b,h2b,h1b_0,h2b_0); 
      long h2b_1,h1b_1; 
      z->restricted_2(h2b,h1b,h2b_1,h1b_1); 
      long dim_common=z->get_range(h1b)*z->get_range(h2b); 
      long dima0_sort=1L; 
      long dima0=dim_common*dima0_sort; 
      long dima1_sort=1L; 
      long dima1=dim_common*dima1_sort; 
      if (dima0>0L && dima1>0L) { 
       double* k_a0_sort=z->mem()->malloc_local_double(dima0); 
       double* k_a0=z->mem()->malloc_local_double(dima0); 
       z->f1()->get_block(h2b_0+(z->nab())*(h1b_0),k_a0); 
       z->sort_indices2(k_a0,k_a0_sort,z->get_range(h1b),z->get_range(h2b),1,0,+1.0,false); 
       z->mem()->free_local_double(k_a0); 
       double* k_a1_sort=z->mem()->malloc_local_double(dima1); 
       double* k_a1=z->mem()->malloc_local_double(dima1); 
       in[1]->get_block(h1b_1+z->noab()*(h2b_1),k_a1); 
       z->sort_indices2(k_a1,k_a1_sort,z->get_range(h2b),z->get_range(h1b),0,1,+1.0,false); 
       z->mem()->free_local_double(k_a1); 
       double factor=1.0; 
       z->smith_dgemm(dima0_sort,dima1_sort,dim_common,factor,k_a0_sort,dim_common,k_a1_sort,dim_common,1.0,k_c_sort,dima0_sort); 
       z->mem()->free_local_double(k_a1_sort); 
       z->mem()->free_local_double(k_a0_sort); 
      } 
     } 
    } 
   } 
  } 
  double* k_c=z->mem()->malloc_local_double(dimc); 
  z->sort_indices0(k_c_sort,k_c,1.0,false); 
  out->add_block((0),k_c); 
  z->mem()->free_local_double(k_c); 
  z->mem()->free_local_double(k_c_sort); 
 } 
} 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::offset_smith_0_2(){ 
 
long size=0L; 
for (long h2b=0L;h2b<z->noab();++h2b) { 
 for (long h1b=0L;h1b<z->noab();++h1b) { 
  if (z->get_spin(h2b)==z->get_spin(h1b)) { 
   if ((z->get_sym(h2b)^z->get_sym(h1b))==(z->irrep_t()^(z->irrep_y()^z->irrep_e()))) { 
    if (!z->restricted() || z->get_spin(h2b)+z->get_spin(h1b)!=4L) { 
     in[1]->input_offset(h1b+z->noab()*(h2b),size); 
     size+=z->get_range(h2b)*z->get_range(h1b); 
    } 
   } 
  } 
 } 
} 
in[1]->set_filesize(size); 
in[1]->createfile(); 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::smith_0_3(Ref<Tensor>& out){ 
      
long tileoffset; 
if (out->is_this_local(0L)) { 
 if (z->irrep_e()==(z->irrep_t()^(z->irrep_y()^z->irrep_e()))) { 
  long dimc=1; 
  double* k_c_sort=z->mem()->malloc_local_double(dimc); 
  std::fill(k_c_sort,k_c_sort+(size_t)dimc,0.0); 
  for (long h1b=0L;h1b<z->noab();++h1b) { 
   for (long h2b=h1b;h2b<z->noab();++h2b) { 
    for (long h3b=0L;h3b<z->noab();++h3b) { 
     for (long h4b=h3b;h4b<z->noab();++h4b) { 
      if (z->get_spin(h1b)+z->get_spin(h2b)==z->get_spin(h3b)+z->get_spin(h4b)) { 
       if ((z->get_sym(h1b)^(z->get_sym(h2b)^(z->get_sym(h3b)^z->get_sym(h4b))))==z->irrep_t()) { 
        long h1b_0,h2b_0,h3b_0,h4b_0; 
        z->restricted_4(h1b,h2b,h3b,h4b,h1b_0,h2b_0,h3b_0,h4b_0); 
        long h3b_1,h4b_1,h1b_1,h2b_1; 
        z->restricted_4(h3b,h4b,h1b,h2b,h3b_1,h4b_1,h1b_1,h2b_1); 
        long dim_common=z->get_range(h1b)*z->get_range(h2b)*z->get_range(h3b)*z->get_range(h4b); 
        long dima0_sort=1L; 
        long dima0=dim_common*dima0_sort; 
        long dima1_sort=1L; 
        long dima1=dim_common*dima1_sort; 
        if (dima0>0L && dima1>0L) { 
         double* k_a0_sort=z->mem()->malloc_local_double(dima0); 
         double* k_a0=z->mem()->malloc_local_double(dima0); 
         z->gt2()->get_block(h4b_0+z->noab()*(h3b_0+z->noab()*(h2b_0+z->noab()*(h1b_0))),k_a0); 
         z->sort_indices4(k_a0,k_a0_sort,z->get_range(h1b),z->get_range(h2b),z->get_range(h3b),z->get_range(h4b),3,2,1,0,+1.0,false); 
         z->mem()->free_local_double(k_a0); 
         double* k_a1_sort=z->mem()->malloc_local_double(dima1); 
         double* k_a1=z->mem()->malloc_local_double(dima1); 
         in[1]->get_block(h2b_1+z->noab()*(h1b_1+z->noab()*(h4b_1+z->noab()*(h3b_1))),k_a1); 
         z->sort_indices4(k_a1,k_a1_sort,z->get_range(h3b),z->get_range(h4b),z->get_range(h1b),z->get_range(h2b),1,0,3,2,+1.0,false); 
         z->mem()->free_local_double(k_a1); 
         double factor=1.0; 
         if (h1b==h2b) { 
          factor=factor/2.0; 
         } 
         if (h3b==h4b) { 
          factor=factor/2.0; 
         } 
         z->smith_dgemm(dima0_sort,dima1_sort,dim_common,factor,k_a0_sort,dim_common,k_a1_sort,dim_common,1.0,k_c_sort,dima0_sort); 
         z->mem()->free_local_double(k_a1_sort); 
         z->mem()->free_local_double(k_a0_sort); 
        } 
       } 
      } 
     } 
    } 
   } 
  } 
  double* k_c=z->mem()->malloc_local_double(dimc); 
  z->sort_indices0(k_c_sort,k_c,1.0,false); 
  out->add_block((0),k_c); 
  z->mem()->free_local_double(k_c); 
  z->mem()->free_local_double(k_c_sort); 
 } 
} 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::offset_smith_0_3(){ 
 
long size=0L; 
for (long h3b=0L;h3b<z->noab();++h3b) { 
 for (long h4b=h3b;h4b<z->noab();++h4b) { 
  for (long h1b=0L;h1b<z->noab();++h1b) { 
   for (long h2b=h1b;h2b<z->noab();++h2b) { 
    if (z->get_spin(h3b)+z->get_spin(h4b)==z->get_spin(h1b)+z->get_spin(h2b)) { 
     if ((z->get_sym(h3b)^(z->get_sym(h4b)^(z->get_sym(h1b)^z->get_sym(h2b))))==(z->irrep_y()^z->irrep_e())) { 
      if (!z->restricted() || z->get_spin(h3b)+z->get_spin(h4b)+z->get_spin(h1b)+z->get_spin(h2b)!=8L) { 
       in[1]->input_offset(h2b+z->noab()*(h1b+z->noab()*(h4b+z->noab()*(h3b))),size); 
       size+=z->get_range(h3b)*z->get_range(h4b)*z->get_range(h1b)*z->get_range(h2b); 
      } 
     } 
    } 
   } 
  } 
 } 
} 
in[1]->set_filesize(size); 
in[1]->createfile(); 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::smith_0_4(Ref<Tensor>& out){ 
      
long tileoffset; 
if (out->is_this_local(0L)) { 
 if (z->irrep_e()==(z->irrep_y()^z->irrep_e())) { 
  long dimc=1; 
  double* k_c_sort=z->mem()->malloc_local_double(dimc); 
  std::fill(k_c_sort,k_c_sort+(size_t)dimc,0.0); 
  for (long h1b=0L;h1b<z->noab();++h1b) { 
   for (long h2b=h1b;h2b<z->noab();++h2b) { 
    for (long h3b=0L;h3b<z->noab();++h3b) { 
     for (long h4b=h3b;h4b<z->noab();++h4b) { 
      if (z->get_spin(h1b)+z->get_spin(h2b)==z->get_spin(h3b)+z->get_spin(h4b)) { 
       if ((z->get_sym(h1b)^(z->get_sym(h2b)^(z->get_sym(h3b)^z->get_sym(h4b))))==z->irrep_y()) { 
        long h1b_0,h2b_0,h3b_0,h4b_0; 
        z->restricted_4(h1b,h2b,h3b,h4b,h1b_0,h2b_0,h3b_0,h4b_0); 
        long h3b_1,h4b_1,h1b_1,h2b_1; 
        z->restricted_4(h3b,h4b,h1b,h2b,h3b_1,h4b_1,h1b_1,h2b_1); 
        long dim_common=z->get_range(h1b)*z->get_range(h2b)*z->get_range(h3b)*z->get_range(h4b); 
        long dima0_sort=1L; 
        long dima0=dim_common*dima0_sort; 
        long dima1_sort=1L; 
        long dima1=dim_common*dima1_sort; 
        if (dima0>0L && dima1>0L) { 
         double* k_a0_sort=z->mem()->malloc_local_double(dima0); 
         double* k_a0=z->mem()->malloc_local_double(dima0); 
         z->glambda2()->get_block(h4b_0+z->noab()*(h3b_0+z->noab()*(h2b_0+z->noab()*(h1b_0))),k_a0); 
         z->sort_indices4(k_a0,k_a0_sort,z->get_range(h1b),z->get_range(h2b),z->get_range(h3b),z->get_range(h4b),3,2,1,0,+1.0,false); 
         z->mem()->free_local_double(k_a0); 
         double* k_a1_sort=z->mem()->malloc_local_double(dima1); 
         double* k_a1=z->mem()->malloc_local_double(dima1); 
         in[1]->get_block(h2b_1+z->noab()*(h1b_1+z->noab()*(h4b_1+z->noab()*(h3b_1))),k_a1); 
         z->sort_indices4(k_a1,k_a1_sort,z->get_range(h3b),z->get_range(h4b),z->get_range(h1b),z->get_range(h2b),1,0,3,2,+1.0,false); 
         z->mem()->free_local_double(k_a1); 
         double factor=1.0; 
         if (h1b==h2b) { 
          factor=factor/2.0; 
         } 
         if (h3b==h4b) { 
          factor=factor/2.0; 
         } 
         z->smith_dgemm(dima0_sort,dima1_sort,dim_common,factor,k_a0_sort,dim_common,k_a1_sort,dim_common,1.0,k_c_sort,dima0_sort); 
         z->mem()->free_local_double(k_a1_sort); 
         z->mem()->free_local_double(k_a0_sort); 
        } 
       } 
      } 
     } 
    } 
   } 
  } 
  double* k_c=z->mem()->malloc_local_double(dimc); 
  z->sort_indices0(k_c_sort,k_c,1.0,false); 
  out->add_block((0),k_c); 
  z->mem()->free_local_double(k_c); 
  z->mem()->free_local_double(k_c_sort); 
 } 
} 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::smith_0_4_0(){ 
      
for (long h3b=0L;h3b<z->noab();++h3b) { 
 for (long h4b=h3b;h4b<z->noab();++h4b) { 
  for (long h1b=0L;h1b<z->noab();++h1b) { 
   for (long h2b=h1b;h2b<z->noab();++h2b) { 
    long tileoffset; 
    tileoffset=(h2b+z->noab()*(h1b+z->noab()*(h4b+z->noab()*(h3b)))); 
    if (in[1]->is_this_local(tileoffset)) { 
     if (!z->restricted() || z->get_spin(h3b)+z->get_spin(h4b)+z->get_spin(h1b)+z->get_spin(h2b)!=8L) { 
      if (z->get_spin(h3b)+z->get_spin(h4b)==z->get_spin(h1b)+z->get_spin(h2b)) { 
       if ((z->get_sym(h3b)^(z->get_sym(h4b)^(z->get_sym(h1b)^z->get_sym(h2b))))==z->irrep_e()) { 
        long dimc=z->get_range(h3b)*z->get_range(h4b)*z->get_range(h1b)*z->get_range(h2b); 
        long h3b_0,h4b_0,h1b_0,h2b_0; 
        z->restricted_4(h3b,h4b,h1b,h2b,h3b_0,h4b_0,h1b_0,h2b_0); 
        long dim_common=1L; 
        long dima0_sort=z->get_range(h3b)*z->get_range(h4b)*z->get_range(h1b)*z->get_range(h2b); 
        long dima0=dim_common*dima0_sort; 
        if (dima0>0L) { 
         double* k_a0_sort=z->mem()->malloc_local_double(dima0); 
         double* k_a0=z->mem()->malloc_local_double(dima0); 
         z->vd2()->get_block(h2b_0+(z->nab())*(h1b_0+(z->nab())*(h4b_0+z->noab()*(h3b_0))),k_a0); 
         z->sort_indices4(k_a0,k_a0_sort,z->get_range(h3b),z->get_range(h4b),z->get_range(h1b),z->get_range(h2b),0,1,2,3,+1.0,false); 
         z->mem()->free_local_double(k_a0); 
         double* k_c=z->mem()->malloc_local_double(dimc); 
         z->sort_indices4(k_a0_sort,k_c,z->get_range(h3b),z->get_range(h4b),z->get_range(h1b),z->get_range(h2b),0,1,2,3,+1.0,false); 
         in[1]->add_block(h2b+z->noab()*(h1b+z->noab()*(h4b+z->noab()*(h3b))),k_c); 
         z->mem()->free_local_double(k_c); 
         z->mem()->free_local_double(k_a0_sort); 
        } 
       } 
      } 
     } 
    } 
   } 
  } 
 } 
} 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::offset_smith_0_4(){ 
 
long size=0L; 
for (long h3b=0L;h3b<z->noab();++h3b) { 
 for (long h4b=h3b;h4b<z->noab();++h4b) { 
  for (long h1b=0L;h1b<z->noab();++h1b) { 
   for (long h2b=h1b;h2b<z->noab();++h2b) { 
    if (z->get_spin(h3b)+z->get_spin(h4b)==z->get_spin(h1b)+z->get_spin(h2b)) { 
     if ((z->get_sym(h3b)^(z->get_sym(h4b)^(z->get_sym(h1b)^z->get_sym(h2b))))==(z->irrep_t()^z->irrep_e())) { 
      if (!z->restricted() || z->get_spin(h3b)+z->get_spin(h4b)+z->get_spin(h1b)+z->get_spin(h2b)!=8L) { 
       in[1]->input_offset(h2b+z->noab()*(h1b+z->noab()*(h4b+z->noab()*(h3b))),size); 
       size+=z->get_range(h3b)*z->get_range(h4b)*z->get_range(h1b)*z->get_range(h2b); 
      } 
     } 
    } 
   } 
  } 
 } 
} 
in[1]->set_filesize(size); 
in[1]->createfile(); 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::smith_0_5(Ref<Tensor>& out){ 
      
long tileoffset; 
if (out->is_this_local(0L)) { 
 if (z->irrep_e()==(z->irrep_t()^(z->irrep_y()^z->irrep_v()))) { 
  long dimc=1; 
  double* k_c_sort=z->mem()->malloc_local_double(dimc); 
  std::fill(k_c_sort,k_c_sort+(size_t)dimc,0.0); 
  for (long h2b=0L;h2b<z->noab();++h2b) { 
   for (long p1b=z->noab();p1b<z->noab()+z->nvab();++p1b) { 
    if (z->get_spin(p1b)==z->get_spin(h2b)) { 
     if ((z->get_sym(p1b)^z->get_sym(h2b))==z->irrep_t()) { 
      long p1b_0,h2b_0; 
      z->restricted_2(p1b,h2b,p1b_0,h2b_0); 
      long h2b_1,p1b_1; 
      z->restricted_2(h2b,p1b,h2b_1,p1b_1); 
      long dim_common=z->get_range(h2b)*z->get_range(p1b); 
      long dima0_sort=1L; 
      long dima0=dim_common*dima0_sort; 
      long dima1_sort=1L; 
      long dima1=dim_common*dima1_sort; 
      if (dima0>0L && dima1>0L) { 
       double* k_a0_sort=z->mem()->malloc_local_double(dima0); 
       double* k_a0=z->mem()->malloc_local_double(dima0); 
       z->t1()->get_block(h2b_0+z->noab()*(p1b_0-z->noab()),k_a0); 
       z->sort_indices2(k_a0,k_a0_sort,z->get_range(p1b),z->get_range(h2b),0,1,+1.0,false); 
       z->mem()->free_local_double(k_a0); 
       double* k_a1_sort=z->mem()->malloc_local_double(dima1); 
       double* k_a1=z->mem()->malloc_local_double(dima1); 
       in[1]->get_block(p1b_1-z->noab()+z->nvab()*(h2b_1),k_a1); 
       z->sort_indices2(k_a1,k_a1_sort,z->get_range(h2b),z->get_range(p1b),1,0,+1.0,false); 
       z->mem()->free_local_double(k_a1); 
       double factor=1.0; 
       z->smith_dgemm(dima0_sort,dima1_sort,dim_common,factor,k_a0_sort,dim_common,k_a1_sort,dim_common,1.0,k_c_sort,dima0_sort); 
       z->mem()->free_local_double(k_a1_sort); 
       z->mem()->free_local_double(k_a0_sort); 
      } 
     } 
    } 
   } 
  } 
  double* k_c=z->mem()->malloc_local_double(dimc); 
  z->sort_indices0(k_c_sort,k_c,1.0,false); 
  out->add_block((0),k_c); 
  z->mem()->free_local_double(k_c); 
  z->mem()->free_local_double(k_c_sort); 
 } 
} 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::offset_smith_0_5(){ 
 
long size=0L; 
for (long h2b=0L;h2b<z->noab();++h2b) { 
 for (long p1b=z->noab();p1b<z->noab()+z->nvab();++p1b) { 
  if (z->get_spin(h2b)==z->get_spin(p1b)) { 
   if ((z->get_sym(h2b)^z->get_sym(p1b))==(z->irrep_y()^z->irrep_v())) { 
    if (!z->restricted() || z->get_spin(h2b)+z->get_spin(p1b)!=4L) { 
     in[1]->input_offset(p1b-z->noab()+z->nvab()*(h2b),size); 
     size+=z->get_range(h2b)*z->get_range(p1b); 
    } 
   } 
  } 
 } 
} 
in[1]->set_filesize(size); 
in[1]->createfile(); 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::smith_0_9(Ref<Tensor>& out){ 
      
long tileoffset; 
if (out->is_this_local(0L)) { 
 if (z->irrep_e()==(z->irrep_t()^(z->irrep_y()^z->irrep_v()))) { 
  long dimc=1; 
  double* k_c_sort=z->mem()->malloc_local_double(dimc); 
  std::fill(k_c_sort,k_c_sort+(size_t)dimc,0.0); 
  for (long h3b=0L;h3b<z->noab();++h3b) { 
   for (long h4b=h3b;h4b<z->noab();++h4b) { 
    for (long p1b=z->noab();p1b<z->noab()+z->nvab();++p1b) { 
     for (long p2b=p1b;p2b<z->noab()+z->nvab();++p2b) { 
      if (z->get_spin(p1b)+z->get_spin(p2b)==z->get_spin(h3b)+z->get_spin(h4b)) { 
       if ((z->get_sym(p1b)^(z->get_sym(p2b)^(z->get_sym(h3b)^z->get_sym(h4b))))==z->irrep_t()) { 
        long p1b_0,p2b_0,h3b_0,h4b_0; 
        z->restricted_4(p1b,p2b,h3b,h4b,p1b_0,p2b_0,h3b_0,h4b_0); 
        long h3b_1,h4b_1,p1b_1,p2b_1; 
        z->restricted_4(h3b,h4b,p1b,p2b,h3b_1,h4b_1,p1b_1,p2b_1); 
        long dim_common=z->get_range(h3b)*z->get_range(h4b)*z->get_range(p1b)*z->get_range(p2b); 
        long dima0_sort=1L; 
        long dima0=dim_common*dima0_sort; 
        long dima1_sort=1L; 
        long dima1=dim_common*dima1_sort; 
        if (dima0>0L && dima1>0L) { 
         double* k_a0_sort=z->mem()->malloc_local_double(dima0); 
         double* k_a0=z->mem()->malloc_local_double(dima0); 
         z->t2()->get_block(h4b_0+z->noab()*(h3b_0+z->noab()*(p2b_0-z->noab()+z->nvab()*(p1b_0-z->noab()))),k_a0); 
         z->sort_indices4(k_a0,k_a0_sort,z->get_range(p1b),z->get_range(p2b),z->get_range(h3b),z->get_range(h4b),1,0,3,2,+1.0,false); 
         z->mem()->free_local_double(k_a0); 
         double* k_a1_sort=z->mem()->malloc_local_double(dima1); 
         double* k_a1=z->mem()->malloc_local_double(dima1); 
         in[1]->get_block(p2b_1-z->noab()+z->nvab()*(p1b_1-z->noab()+z->nvab()*(h4b_1+z->noab()*(h3b_1))),k_a1); 
         z->sort_indices4(k_a1,k_a1_sort,z->get_range(h3b),z->get_range(h4b),z->get_range(p1b),z->get_range(p2b),3,2,1,0,+1.0,false); 
         z->mem()->free_local_double(k_a1); 
         double factor=1.0; 
         if (h3b==h4b) { 
          factor=factor/2.0; 
         } 
         if (p1b==p2b) { 
          factor=factor/2.0; 
         } 
         z->smith_dgemm(dima0_sort,dima1_sort,dim_common,factor,k_a0_sort,dim_common,k_a1_sort,dim_common,1.0,k_c_sort,dima0_sort); 
         z->mem()->free_local_double(k_a1_sort); 
         z->mem()->free_local_double(k_a0_sort); 
        } 
       } 
      } 
     } 
    } 
   } 
  } 
  double* k_c=z->mem()->malloc_local_double(dimc); 
  z->sort_indices0(k_c_sort,k_c,1.0,false); 
  out->add_block((0),k_c); 
  z->mem()->free_local_double(k_c); 
  z->mem()->free_local_double(k_c_sort); 
 } 
} 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::offset_smith_0_9(){ 
 
long size=0L; 
for (long h3b=0L;h3b<z->noab();++h3b) { 
 for (long h4b=h3b;h4b<z->noab();++h4b) { 
  for (long p1b=z->noab();p1b<z->noab()+z->nvab();++p1b) { 
   for (long p2b=p1b;p2b<z->noab()+z->nvab();++p2b) { 
    if (z->get_spin(h3b)+z->get_spin(h4b)==z->get_spin(p1b)+z->get_spin(p2b)) { 
     if ((z->get_sym(h3b)^(z->get_sym(h4b)^(z->get_sym(p1b)^z->get_sym(p2b))))==(z->irrep_y()^z->irrep_v())) { 
      if (!z->restricted() || z->get_spin(h3b)+z->get_spin(h4b)+z->get_spin(p1b)+z->get_spin(p2b)!=8L) { 
       in[1]->input_offset(p2b-z->noab()+z->nvab()*(p1b-z->noab()+z->nvab()*(h4b+z->noab()*(h3b))),size); 
       size+=z->get_range(h3b)*z->get_range(h4b)*z->get_range(p1b)*z->get_range(p2b); 
      } 
     } 
    } 
   } 
  } 
 } 
} 
in[1]->set_filesize(size); 
in[1]->createfile(); 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::smith_1_10(){ 
      
for (long h3b=0L;h3b<z->noab();++h3b) { 
 for (long h4b=h3b;h4b<z->noab();++h4b) { 
  for (long h1b=0L;h1b<z->noab();++h1b) { 
   for (long h2b=h1b;h2b<z->noab();++h2b) { 
    long tileoffset; 
    tileoffset=(h2b+z->noab()*(h1b+z->noab()*(h4b+z->noab()*(h3b)))); 
    if (in[1]->is_this_local(tileoffset)) { 
     if (!z->restricted() || z->get_spin(h3b)+z->get_spin(h4b)+z->get_spin(h1b)+z->get_spin(h2b)!=8L) { 
      if (z->get_spin(h3b)+z->get_spin(h4b)==z->get_spin(h1b)+z->get_spin(h2b)) { 
       if ((z->get_sym(h3b)^(z->get_sym(h4b)^(z->get_sym(h1b)^z->get_sym(h2b))))==(z->irrep_t()^z->irrep_e())) { 
        long dimc=z->get_range(h3b)*z->get_range(h4b)*z->get_range(h1b)*z->get_range(h2b); 
        double* k_c_sort=z->mem()->malloc_local_double(dimc); 
        std::fill(k_c_sort,k_c_sort+(size_t)dimc,0.0); 
        for (long p5b=z->noab();p5b<z->noab()+z->nvab();++p5b) { 
         for (long p6b=p5b;p6b<z->noab()+z->nvab();++p6b) { 
          if (z->get_spin(p5b)+z->get_spin(p6b)==z->get_spin(h1b)+z->get_spin(h2b)) { 
           if ((z->get_sym(p5b)^(z->get_sym(p6b)^(z->get_sym(h1b)^z->get_sym(h2b))))==z->irrep_t()) { 
            long p5b_0,p6b_0,h1b_0,h2b_0; 
            z->restricted_4(p5b,p6b,h1b,h2b,p5b_0,p6b_0,h1b_0,h2b_0); 
            long h3b_1,h4b_1,p5b_1,p6b_1; 
            z->restricted_4(h3b,h4b,p5b,p6b,h3b_1,h4b_1,p5b_1,p6b_1); 
            long dim_common=z->get_range(p5b)*z->get_range(p6b); 
            long dima0_sort=z->get_range(h1b)*z->get_range(h2b); 
            long dima0=dim_common*dima0_sort; 
            long dima1_sort=z->get_range(h3b)*z->get_range(h4b); 
            long dima1=dim_common*dima1_sort; 
            if (dima0>0L && dima1>0L) { 
             double* k_a0_sort=z->mem()->malloc_local_double(dima0); 
             double* k_a0=z->mem()->malloc_local_double(dima0); 
             z->t2()->get_block(h2b_0+z->noab()*(h1b_0+z->noab()*(p6b_0-z->noab()+z->nvab()*(p5b_0-z->noab()))),k_a0); 
             z->sort_indices4(k_a0,k_a0_sort,z->get_range(p5b),z->get_range(p6b),z->get_range(h1b),z->get_range(h2b),3,2,1,0,+1.0,false); 
             z->mem()->free_local_double(k_a0); 
             double* k_a1_sort=z->mem()->malloc_local_double(dima1); 
             double* k_a1=z->mem()->malloc_local_double(dima1); 
             z->vd2()->get_block(p6b_1+(z->nab())*(p5b_1+(z->nab())*(h4b_1+z->noab()*(h3b_1))),k_a1); 
             z->sort_indices4(k_a1,k_a1_sort,z->get_range(h3b),z->get_range(h4b),z->get_range(p5b),z->get_range(p6b),1,0,3,2,+1.0,false); 
             z->mem()->free_local_double(k_a1); 
             double factor=1.0; 
             if (p5b==p6b) { 
              factor=factor/2.0; 
             } 
             z->smith_dgemm(dima0_sort,dima1_sort,dim_common,factor,k_a0_sort,dim_common,k_a1_sort,dim_common,1.0,k_c_sort,dima0_sort); 
             z->mem()->free_local_double(k_a1_sort); 
             z->mem()->free_local_double(k_a0_sort); 
            } 
           } 
          } 
         } 
        } 
        double* k_c=z->mem()->malloc_local_double(dimc); 
        z->sort_indices4(k_c_sort,k_c,z->get_range(h4b),z->get_range(h3b),z->get_range(h2b),z->get_range(h1b),1,0,3,2,+0.5/0.5,false); 
        in[1]->add_block(h2b+z->noab()*(h1b+z->noab()*(h4b+z->noab()*(h3b))),k_c); 
        z->mem()->free_local_double(k_c); 
        z->mem()->free_local_double(k_c_sort); 
       } 
      } 
     } 
    } 
   } 
  } 
 } 
} 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::smith_1_12(){ 
      
for (long h2b=0L;h2b<z->noab();++h2b) { 
 for (long p1b=z->noab();p1b<z->noab()+z->nvab();++p1b) { 
  long tileoffset; 
  tileoffset=(p1b-z->noab()+z->nvab()*(h2b)); 
  if (in[1]->is_this_local(tileoffset)) { 
   if (!z->restricted() || z->get_spin(h2b)+z->get_spin(p1b)!=4L) { 
    if (z->get_spin(h2b)==z->get_spin(p1b)) { 
     if ((z->get_sym(h2b)^z->get_sym(p1b))==(z->irrep_v()^z->irrep_v())) { 
      long dimc=z->get_range(h2b)*z->get_range(p1b); 
      double* k_c_sort=z->mem()->malloc_local_double(dimc); 
      std::fill(k_c_sort,k_c_sort+(size_t)dimc,0.0); 
      for (long p4b=z->noab();p4b<z->noab()+z->nvab();++p4b) { 
       for (long q3b=z->noab()+z->nvab();q3b<z->nab();++q3b) { 
        if (z->get_spin(h2b)+z->get_spin(q3b)==z->get_spin(p1b)+z->get_spin(p4b)) { 
         if ((z->get_sym(h2b)^(z->get_sym(q3b)^(z->get_sym(p1b)^z->get_sym(p4b))))==z->irrep_v()) { 
          long h2b_0,q3b_0,p1b_0,p4b_0; 
          z->restricted_4(h2b,q3b,p1b,p4b,h2b_0,q3b_0,p1b_0,p4b_0); 
          long p4b_1,q3b_1; 
          z->restricted_2(p4b,q3b,p4b_1,q3b_1); 
          long dim_common=z->get_range(p4b)*z->get_range(q3b); 
          long dima0_sort=z->get_range(h2b)*z->get_range(p1b); 
          long dima0=dim_common*dima0_sort; 
          long dima1_sort=1L; 
          long dima1=dim_common*dima1_sort; 
          if (dima0>0L && dima1>0L) { 
           double* k_a0_sort=z->mem()->malloc_local_double(dima0); 
           double* k_a0=z->mem()->malloc_local_double(dima0); 
           if (p1b<p4b) { 
            z->v2()->get_block(p4b_0+(z->nab())*(p1b_0+(z->nab())*(q3b_0+(z->nab())*(h2b_0))),k_a0); 
            z->sort_indices4(k_a0,k_a0_sort,z->get_range(h2b),z->get_range(q3b),z->get_range(p1b),z->get_range(p4b),2,0,1,3,+1.0,false); 
           } 
           else if (p4b<=p1b) { 
            z->v2()->get_block(p1b_0+(z->nab())*(p4b_0+(z->nab())*(q3b_0+(z->nab())*(h2b_0))),k_a0); 
            z->sort_indices4(k_a0,k_a0_sort,z->get_range(h2b),z->get_range(q3b),z->get_range(p4b),z->get_range(p1b),3,0,1,2,-1.0,false); 
           } 
           z->mem()->free_local_double(k_a0); 
           double* k_a1_sort=z->mem()->malloc_local_double(dima1); 
           double* k_a1=z->mem()->malloc_local_double(dima1); 
           kn[0]->get_block(q3b_1-z->noab()-z->nvab()+z->ncab()*(p4b_1-z->noab()),k_a1); 
           z->sort_indices2(k_a1,k_a1_sort,z->get_range(p4b),z->get_range(q3b),1,0,+1.0,false); 
           z->mem()->free_local_double(k_a1); 
           double factor=1.0; 
           z->smith_dgemm(dima0_sort,dima1_sort,dim_common,factor,k_a0_sort,dim_common,k_a1_sort,dim_common,1.0,k_c_sort,dima0_sort); 
           z->mem()->free_local_double(k_a1_sort); 
           z->mem()->free_local_double(k_a0_sort); 
          } 
         } 
        } 
       } 
      } 
      double* k_c=z->mem()->malloc_local_double(dimc); 
      z->sort_indices2(k_c_sort,k_c,z->get_range(p1b),z->get_range(h2b),1,0,-1.0,false); 
      in[1]->add_block(p1b-z->noab()+z->nvab()*(h2b),k_c); 
      z->mem()->free_local_double(k_c); 
      z->mem()->free_local_double(k_c_sort); 
     } 
    } 
   } 
  } 
 } 
} 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::smith_1_13(){ 
      
for (long h2b=0L;h2b<z->noab();++h2b) { 
 for (long p1b=z->noab();p1b<z->noab()+z->nvab();++p1b) { 
  long tileoffset; 
  tileoffset=(p1b-z->noab()+z->nvab()*(h2b)); 
  if (in[1]->is_this_local(tileoffset)) { 
   if (!z->restricted() || z->get_spin(h2b)+z->get_spin(p1b)!=4L) { 
    if (z->get_spin(h2b)==z->get_spin(p1b)) { 
     if ((z->get_sym(h2b)^z->get_sym(p1b))==(z->irrep_v()^(z->irrep_t()^z->irrep_y()))) { 
      long dimc=z->get_range(h2b)*z->get_range(p1b); 
      double* k_c_sort=z->mem()->malloc_local_double(dimc); 
      std::fill(k_c_sort,k_c_sort+(size_t)dimc,0.0); 
      for (long h3b=0L;h3b<z->noab();++h3b) { 
       for (long p5b=z->noab();p5b<z->noab()+z->nvab();++p5b) { 
        for (long q4b=z->noab()+z->nvab();q4b<z->nab();++q4b) { 
         if (z->get_spin(h3b)+z->get_spin(q4b)==z->get_spin(p1b)+z->get_spin(p5b)) { 
          if ((z->get_sym(h3b)^(z->get_sym(q4b)^(z->get_sym(p1b)^z->get_sym(p5b))))==z->irrep_v()) { 
           long h3b_0,q4b_0,p1b_0,p5b_0; 
           z->restricted_4(h3b,q4b,p1b,p5b,h3b_0,q4b_0,p1b_0,p5b_0); 
           long h2b_1,p5b_1,h3b_1,q4b_1; 
           z->restricted_4(h2b,p5b,h3b,q4b,h2b_1,p5b_1,h3b_1,q4b_1); 
           long dim_common=z->get_range(h3b)*z->get_range(p5b)*z->get_range(q4b); 
           long dima0_sort=z->get_range(p1b); 
           long dima0=dim_common*dima0_sort; 
           long dima1_sort=z->get_range(h2b); 
           long dima1=dim_common*dima1_sort; 
           if (dima0>0L && dima1>0L) { 
            double* k_a0_sort=z->mem()->malloc_local_double(dima0); 
            double* k_a0=z->mem()->malloc_local_double(dima0); 
            if (p1b<p5b) { 
             z->v2()->get_block(p5b_0+(z->nab())*(p1b_0+(z->nab())*(q4b_0+(z->nab())*(h3b_0))),k_a0); 
             z->sort_indices4(k_a0,k_a0_sort,z->get_range(h3b),z->get_range(q4b),z->get_range(p1b),z->get_range(p5b),2,1,3,0,+1.0,false); 
            } 
            else if (p5b<=p1b) { 
             z->v2()->get_block(p1b_0+(z->nab())*(p5b_0+(z->nab())*(q4b_0+(z->nab())*(h3b_0))),k_a0); 
             z->sort_indices4(k_a0,k_a0_sort,z->get_range(h3b),z->get_range(q4b),z->get_range(p5b),z->get_range(p1b),3,1,2,0,-1.0,false); 
            } 
            z->mem()->free_local_double(k_a0); 
            double* k_a1_sort=z->mem()->malloc_local_double(dima1); 
            double* k_a1=z->mem()->malloc_local_double(dima1); 
            in[2]->get_block(q4b_1-z->noab()-z->nvab()+z->ncab()*(h3b_1+z->noab()*(p5b_1-z->noab()+z->nvab()*(h2b_1))),k_a1); 
            z->sort_indices4(k_a1,k_a1_sort,z->get_range(h2b),z->get_range(p5b),z->get_range(h3b),z->get_range(q4b),0,3,1,2,+1.0,false); 
            z->mem()->free_local_double(k_a1); 
            double factor=1.0; 
            z->smith_dgemm(dima0_sort,dima1_sort,dim_common,factor,k_a0_sort,dim_common,k_a1_sort,dim_common,1.0,k_c_sort,dima0_sort); 
            z->mem()->free_local_double(k_a1_sort); 
            z->mem()->free_local_double(k_a0_sort); 
           } 
          } 
         } 
        } 
       } 
      } 
      double* k_c=z->mem()->malloc_local_double(dimc); 
      z->sort_indices2(k_c_sort,k_c,z->get_range(h2b),z->get_range(p1b),0,1,+1.0,false); 
      in[1]->add_block(p1b-z->noab()+z->nvab()*(h2b),k_c); 
      z->mem()->free_local_double(k_c); 
      z->mem()->free_local_double(k_c_sort); 
     } 
    } 
   } 
  } 
 } 
} 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::offset_smith_1_13(){ 
 
long size=0L; 
for (long h2b=0L;h2b<z->noab();++h2b) { 
 for (long p5b=z->noab();p5b<z->noab()+z->nvab();++p5b) { 
  for (long h3b=0L;h3b<z->noab();++h3b) { 
   for (long q4b=z->noab()+z->nvab();q4b<z->nab();++q4b) { 
    if (z->get_spin(h2b)+z->get_spin(p5b)==z->get_spin(h3b)+z->get_spin(q4b)) { 
     if ((z->get_sym(h2b)^(z->get_sym(p5b)^(z->get_sym(h3b)^z->get_sym(q4b))))==(z->irrep_t()^z->irrep_y())) { 
      if (!z->restricted() || z->get_spin(h2b)+z->get_spin(p5b)+z->get_spin(h3b)+z->get_spin(q4b)!=8L) { 
       in[2]->input_offset(q4b-z->noab()-z->nvab()+z->ncab()*(h3b+z->noab()*(p5b-z->noab()+z->nvab()*(h2b))),size); 
       size+=z->get_range(h2b)*z->get_range(p5b)*z->get_range(h3b)*z->get_range(q4b); 
      } 
     } 
    } 
   } 
  } 
 } 
} 
in[2]->set_filesize(size); 
in[2]->createfile(); 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::smith_1_2(){ 
      
for (long h2b=0L;h2b<z->noab();++h2b) { 
 for (long h1b=0L;h1b<z->noab();++h1b) { 
  long tileoffset; 
  tileoffset=(h1b+z->noab()*(h2b)); 
  if (in[1]->is_this_local(tileoffset)) { 
   if (!z->restricted() || z->get_spin(h2b)+z->get_spin(h1b)!=4L) { 
    if (z->get_spin(h2b)==z->get_spin(h1b)) { 
     if ((z->get_sym(h2b)^z->get_sym(h1b))==(z->irrep_t()^(z->irrep_y()^z->irrep_e()))) { 
      long dimc=z->get_range(h2b)*z->get_range(h1b); 
      double* k_c_sort=z->mem()->malloc_local_double(dimc); 
      std::fill(k_c_sort,k_c_sort+(size_t)dimc,0.0); 
      for (long h3b=0L;h3b<z->noab();++h3b) { 
       for (long h4b=h3b;h4b<z->noab();++h4b) { 
        for (long h5b=0L;h5b<z->noab();++h5b) { 
         if (z->get_spin(h3b)+z->get_spin(h4b)==z->get_spin(h1b)+z->get_spin(h5b)) { 
          if ((z->get_sym(h3b)^(z->get_sym(h4b)^(z->get_sym(h1b)^z->get_sym(h5b))))==z->irrep_t()) { 
           long h3b_0,h4b_0,h1b_0,h5b_0; 
           z->restricted_4(h3b,h4b,h1b,h5b,h3b_0,h4b_0,h1b_0,h5b_0); 
           long h2b_1,h5b_1,h3b_1,h4b_1; 
           z->restricted_4(h2b,h5b,h3b,h4b,h2b_1,h5b_1,h3b_1,h4b_1); 
           long dim_common=z->get_range(h3b)*z->get_range(h4b)*z->get_range(h5b); 
           long dima0_sort=z->get_range(h1b); 
           long dima0=dim_common*dima0_sort; 
           long dima1_sort=z->get_range(h2b); 
           long dima1=dim_common*dima1_sort; 
           if (dima0>0L && dima1>0L) { 
            double* k_a0_sort=z->mem()->malloc_local_double(dima0); 
            double* k_a0=z->mem()->malloc_local_double(dima0); 
            if (h1b<h5b) { 
             z->gt2()->get_block(h5b_0+z->noab()*(h1b_0+z->noab()*(h4b_0+z->noab()*(h3b_0))),k_a0); 
             z->sort_indices4(k_a0,k_a0_sort,z->get_range(h3b),z->get_range(h4b),z->get_range(h1b),z->get_range(h5b),2,3,1,0,+1.0,false); 
            } 
            else if (h5b<=h1b) { 
             z->gt2()->get_block(h1b_0+z->noab()*(h5b_0+z->noab()*(h4b_0+z->noab()*(h3b_0))),k_a0); 
             z->sort_indices4(k_a0,k_a0_sort,z->get_range(h3b),z->get_range(h4b),z->get_range(h5b),z->get_range(h1b),3,2,1,0,-1.0,false); 
            } 
            z->mem()->free_local_double(k_a0); 
            double* k_a1_sort=z->mem()->malloc_local_double(dima1); 
            double* k_a1=z->mem()->malloc_local_double(dima1); 
            if (h2b<h5b) { 
             in[2]->get_block(h4b_1+z->noab()*(h3b_1+z->noab()*(h5b_1+z->noab()*(h2b_1))),k_a1); 
             z->sort_indices4(k_a1,k_a1_sort,z->get_range(h2b),z->get_range(h5b),z->get_range(h3b),z->get_range(h4b),0,1,3,2,+1.0,false); 
            } 
            else if (h5b<=h2b) { 
             in[2]->get_block(h4b_1+z->noab()*(h3b_1+z->noab()*(h2b_1+z->noab()*(h5b_1))),k_a1); 
             z->sort_indices4(k_a1,k_a1_sort,z->get_range(h5b),z->get_range(h2b),z->get_range(h3b),z->get_range(h4b),1,0,3,2,-1.0,false); 
            } 
            z->mem()->free_local_double(k_a1); 
            double factor=1.0; 
            if (h3b==h4b) { 
             factor=factor/2.0; 
            } 
            z->smith_dgemm(dima0_sort,dima1_sort,dim_common,factor,k_a0_sort,dim_common,k_a1_sort,dim_common,1.0,k_c_sort,dima0_sort); 
            z->mem()->free_local_double(k_a1_sort); 
            z->mem()->free_local_double(k_a0_sort); 
           } 
          } 
         } 
        } 
       } 
      } 
      double* k_c=z->mem()->malloc_local_double(dimc); 
      z->sort_indices2(k_c_sort,k_c,z->get_range(h2b),z->get_range(h1b),0,1,+0.5/0.5,false); 
      in[1]->add_block(h1b+z->noab()*(h2b),k_c); 
      z->mem()->free_local_double(k_c); 
      z->mem()->free_local_double(k_c_sort); 
     } 
    } 
   } 
  } 
 } 
} 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::offset_smith_1_2(){ 
 
long size=0L; 
for (long h2b=0L;h2b<z->noab();++h2b) { 
 for (long h5b=h2b;h5b<z->noab();++h5b) { 
  for (long h3b=0L;h3b<z->noab();++h3b) { 
   for (long h4b=h3b;h4b<z->noab();++h4b) { 
    if (z->get_spin(h2b)+z->get_spin(h5b)==z->get_spin(h3b)+z->get_spin(h4b)) { 
     if ((z->get_sym(h2b)^(z->get_sym(h5b)^(z->get_sym(h3b)^z->get_sym(h4b))))==(z->irrep_y()^z->irrep_e())) { 
      if (!z->restricted() || z->get_spin(h2b)+z->get_spin(h5b)+z->get_spin(h3b)+z->get_spin(h4b)!=8L) { 
       in[2]->input_offset(h4b+z->noab()*(h3b+z->noab()*(h5b+z->noab()*(h2b))),size); 
       size+=z->get_range(h2b)*z->get_range(h5b)*z->get_range(h3b)*z->get_range(h4b); 
      } 
     } 
    } 
   } 
  } 
 } 
} 
in[2]->set_filesize(size); 
in[2]->createfile(); 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::smith_1_3(){ 
      
for (long h3b=0L;h3b<z->noab();++h3b) { 
 for (long h4b=h3b;h4b<z->noab();++h4b) { 
  for (long h1b=0L;h1b<z->noab();++h1b) { 
   for (long h2b=h1b;h2b<z->noab();++h2b) { 
    long tileoffset; 
    tileoffset=(h2b+z->noab()*(h1b+z->noab()*(h4b+z->noab()*(h3b)))); 
    if (in[1]->is_this_local(tileoffset)) { 
     if (!z->restricted() || z->get_spin(h3b)+z->get_spin(h4b)+z->get_spin(h1b)+z->get_spin(h2b)!=8L) { 
      if (z->get_spin(h3b)+z->get_spin(h4b)==z->get_spin(h1b)+z->get_spin(h2b)) { 
       if ((z->get_sym(h3b)^(z->get_sym(h4b)^(z->get_sym(h1b)^z->get_sym(h2b))))==(z->irrep_y()^z->irrep_e())) { 
        long dimc=z->get_range(h3b)*z->get_range(h4b)*z->get_range(h1b)*z->get_range(h2b); 
        double* k_c_sort=z->mem()->malloc_local_double(dimc); 
        std::fill(k_c_sort,k_c_sort+(size_t)dimc,0.0); 
        for (long h5b=0L;h5b<z->noab();++h5b) { 
         for (long h6b=h5b;h6b<z->noab();++h6b) { 
          if (z->get_spin(h3b)+z->get_spin(h4b)==z->get_spin(h5b)+z->get_spin(h6b)) { 
           if ((z->get_sym(h3b)^(z->get_sym(h4b)^(z->get_sym(h5b)^z->get_sym(h6b))))==z->irrep_y()) { 
            long h3b_0,h4b_0,h5b_0,h6b_0; 
            z->restricted_4(h3b,h4b,h5b,h6b,h3b_0,h4b_0,h5b_0,h6b_0); 
            long h5b_1,h6b_1,h1b_1,h2b_1; 
            z->restricted_4(h5b,h6b,h1b,h2b,h5b_1,h6b_1,h1b_1,h2b_1); 
            long dim_common=z->get_range(h5b)*z->get_range(h6b); 
            long dima0_sort=z->get_range(h3b)*z->get_range(h4b); 
            long dima0=dim_common*dima0_sort; 
            long dima1_sort=z->get_range(h1b)*z->get_range(h2b); 
            long dima1=dim_common*dima1_sort; 
            if (dima0>0L && dima1>0L) { 
             double* k_a0_sort=z->mem()->malloc_local_double(dima0); 
             double* k_a0=z->mem()->malloc_local_double(dima0); 
             z->glambda2()->get_block(h6b_0+z->noab()*(h5b_0+z->noab()*(h4b_0+z->noab()*(h3b_0))),k_a0); 
             z->sort_indices4(k_a0,k_a0_sort,z->get_range(h3b),z->get_range(h4b),z->get_range(h5b),z->get_range(h6b),1,0,3,2,+1.0,false); 
             z->mem()->free_local_double(k_a0); 
             double* k_a1_sort=z->mem()->malloc_local_double(dima1); 
             double* k_a1=z->mem()->malloc_local_double(dima1); 
             z->bs2()->get_block(h2b_1+z->noab()*(h1b_1+z->noab()*(h6b_1+z->noab()*(h5b_1))),k_a1); 
             z->sort_indices4(k_a1,k_a1_sort,z->get_range(h5b),z->get_range(h6b),z->get_range(h1b),z->get_range(h2b),3,2,1,0,+1.0,false); 
             z->mem()->free_local_double(k_a1); 
             double factor=1.0; 
             if (h5b==h6b) { 
              factor=factor/2.0; 
             } 
             z->smith_dgemm(dima0_sort,dima1_sort,dim_common,factor,k_a0_sort,dim_common,k_a1_sort,dim_common,1.0,k_c_sort,dima0_sort); 
             z->mem()->free_local_double(k_a1_sort); 
             z->mem()->free_local_double(k_a0_sort); 
            } 
           } 
          } 
         } 
        } 
        double* k_c=z->mem()->malloc_local_double(dimc); 
        z->sort_indices4(k_c_sort,k_c,z->get_range(h2b),z->get_range(h1b),z->get_range(h4b),z->get_range(h3b),3,2,1,0,+0.5/0.5,false); 
        in[1]->add_block(h2b+z->noab()*(h1b+z->noab()*(h4b+z->noab()*(h3b))),k_c); 
        z->mem()->free_local_double(k_c); 
        z->mem()->free_local_double(k_c_sort); 
       } 
      } 
     } 
    } 
   } 
  } 
 } 
} 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::smith_1_5(){ 
      
for (long h2b=0L;h2b<z->noab();++h2b) { 
 for (long p1b=z->noab();p1b<z->noab()+z->nvab();++p1b) { 
  long tileoffset; 
  tileoffset=(p1b-z->noab()+z->nvab()*(h2b)); 
  if (in[1]->is_this_local(tileoffset)) { 
   if (!z->restricted() || z->get_spin(h2b)+z->get_spin(p1b)!=4L) { 
    if (z->get_spin(h2b)==z->get_spin(p1b)) { 
     if ((z->get_sym(h2b)^z->get_sym(p1b))==(z->irrep_y()^z->irrep_v())) { 
      long dimc=z->get_range(h2b)*z->get_range(p1b); 
      double* k_c_sort=z->mem()->malloc_local_double(dimc); 
      std::fill(k_c_sort,k_c_sort+(size_t)dimc,0.0); 
      for (long h3b=0L;h3b<z->noab();++h3b) { 
       for (long h4b=h3b;h4b<z->noab();++h4b) { 
        for (long q5b=z->noab()+z->nvab();q5b<z->nab();++q5b) { 
         if (z->get_spin(h3b)+z->get_spin(h4b)==z->get_spin(p1b)+z->get_spin(q5b)) { 
          if ((z->get_sym(h3b)^(z->get_sym(h4b)^(z->get_sym(p1b)^z->get_sym(q5b))))==z->irrep_y()) { 
           long h3b_0,h4b_0,p1b_0,q5b_0; 
           z->restricted_4(h3b,h4b,p1b,q5b,h3b_0,h4b_0,p1b_0,q5b_0); 
           long h2b_1,q5b_1,h3b_1,h4b_1; 
           z->restricted_4(h2b,q5b,h3b,h4b,h2b_1,q5b_1,h3b_1,h4b_1); 
           long dim_common=z->get_range(h3b)*z->get_range(h4b)*z->get_range(q5b); 
           long dima0_sort=z->get_range(p1b); 
           long dima0=dim_common*dima0_sort; 
           long dima1_sort=z->get_range(h2b); 
           long dima1=dim_common*dima1_sort; 
           if (dima0>0L && dima1>0L) { 
            double* k_a0_sort=z->mem()->malloc_local_double(dima0); 
            double* k_a0=z->mem()->malloc_local_double(dima0); 
            z->ly()->get_block(q5b_0-z->noab()-z->nvab()+z->ncab()*(p1b_0-z->noab()+z->nvab()*(h4b_0+z->noab()*(h3b_0))),k_a0); 
            z->sort_indices4(k_a0,k_a0_sort,z->get_range(h3b),z->get_range(h4b),z->get_range(p1b),z->get_range(q5b),2,3,1,0,+1.0,false); 
            z->mem()->free_local_double(k_a0); 
            double* k_a1_sort=z->mem()->malloc_local_double(dima1); 
            double* k_a1=z->mem()->malloc_local_double(dima1); 
            in[2]->get_block(h4b_1+z->noab()*(h3b_1+z->noab()*(q5b_1-z->noab()-z->nvab()+z->ncab()*(h2b_1))),k_a1); 
            z->sort_indices4(k_a1,k_a1_sort,z->get_range(h2b),z->get_range(q5b),z->get_range(h3b),z->get_range(h4b),0,1,3,2,+1.0,false); 
            z->mem()->free_local_double(k_a1); 
            double factor=1.0; 
            if (h3b==h4b) { 
             factor=factor/2.0; 
            } 
            z->smith_dgemm(dima0_sort,dima1_sort,dim_common,factor,k_a0_sort,dim_common,k_a1_sort,dim_common,1.0,k_c_sort,dima0_sort); 
            z->mem()->free_local_double(k_a1_sort); 
            z->mem()->free_local_double(k_a0_sort); 
           } 
          } 
         } 
        } 
       } 
      } 
      double* k_c=z->mem()->malloc_local_double(dimc); 
      z->sort_indices2(k_c_sort,k_c,z->get_range(h2b),z->get_range(p1b),0,1,+0.5/0.5,false); 
      in[1]->add_block(p1b-z->noab()+z->nvab()*(h2b),k_c); 
      z->mem()->free_local_double(k_c); 
      z->mem()->free_local_double(k_c_sort); 
     } 
    } 
   } 
  } 
 } 
} 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::smith_1_5_0(){ 
      
for (long h2b=0L;h2b<z->noab();++h2b) { 
 for (long q5b=z->noab()+z->nvab();q5b<z->nab();++q5b) { 
  for (long h3b=0L;h3b<z->noab();++h3b) { 
   for (long h4b=h3b;h4b<z->noab();++h4b) { 
    long tileoffset; 
    tileoffset=(h4b+z->noab()*(h3b+z->noab()*(q5b-z->noab()-z->nvab()+z->ncab()*(h2b)))); 
    if (in[2]->is_this_local(tileoffset)) { 
     if (!z->restricted() || z->get_spin(h2b)+z->get_spin(q5b)+z->get_spin(h3b)+z->get_spin(h4b)!=8L) { 
      if (z->get_spin(h2b)+z->get_spin(q5b)==z->get_spin(h3b)+z->get_spin(h4b)) { 
       if ((z->get_sym(h2b)^(z->get_sym(q5b)^(z->get_sym(h3b)^z->get_sym(h4b))))==z->irrep_v()) { 
        long dimc=z->get_range(h2b)*z->get_range(q5b)*z->get_range(h3b)*z->get_range(h4b); 
        long h2b_0,q5b_0,h3b_0,h4b_0; 
        z->restricted_4(h2b,q5b,h3b,h4b,h2b_0,q5b_0,h3b_0,h4b_0); 
        long dim_common=1L; 
        long dima0_sort=z->get_range(h2b)*z->get_range(q5b)*z->get_range(h3b)*z->get_range(h4b); 
        long dima0=dim_common*dima0_sort; 
        if (dima0>0L) { 
         double* k_a0_sort=z->mem()->malloc_local_double(dima0); 
         double* k_a0=z->mem()->malloc_local_double(dima0); 
         z->v2()->get_block(h4b_0+(z->nab())*(h3b_0+(z->nab())*(q5b_0+(z->nab())*(h2b_0))),k_a0); 
         z->sort_indices4(k_a0,k_a0_sort,z->get_range(h2b),z->get_range(q5b),z->get_range(h3b),z->get_range(h4b),0,1,2,3,+1.0,false); 
         z->mem()->free_local_double(k_a0); 
         double* k_c=z->mem()->malloc_local_double(dimc); 
         z->sort_indices4(k_a0_sort,k_c,z->get_range(h2b),z->get_range(q5b),z->get_range(h3b),z->get_range(h4b),0,1,2,3,-1.0,false); 
         in[2]->add_block(h4b+z->noab()*(h3b+z->noab()*(q5b-z->noab()-z->nvab()+z->ncab()*(h2b))),k_c); 
         z->mem()->free_local_double(k_c); 
         z->mem()->free_local_double(k_a0_sort); 
        } 
       } 
      } 
     } 
    } 
   } 
  } 
 } 
} 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::offset_smith_1_5(){ 
 
long size=0L; 
for (long h2b=0L;h2b<z->noab();++h2b) { 
 for (long q5b=z->noab()+z->nvab();q5b<z->nab();++q5b) { 
  for (long h3b=0L;h3b<z->noab();++h3b) { 
   for (long h4b=h3b;h4b<z->noab();++h4b) { 
    if (z->get_spin(h2b)+z->get_spin(q5b)==z->get_spin(h3b)+z->get_spin(h4b)) { 
     if ((z->get_sym(h2b)^(z->get_sym(q5b)^(z->get_sym(h3b)^z->get_sym(h4b))))==(z->irrep_t()^z->irrep_v())) { 
      if (!z->restricted() || z->get_spin(h2b)+z->get_spin(q5b)+z->get_spin(h3b)+z->get_spin(h4b)!=8L) { 
       in[2]->input_offset(h4b+z->noab()*(h3b+z->noab()*(q5b-z->noab()-z->nvab()+z->ncab()*(h2b))),size); 
       size+=z->get_range(h2b)*z->get_range(q5b)*z->get_range(h3b)*z->get_range(h4b); 
      } 
     } 
    } 
   } 
  } 
 } 
} 
in[2]->set_filesize(size); 
in[2]->createfile(); 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::smith_1_6(){ 
      
for (long h2b=0L;h2b<z->noab();++h2b) { 
 for (long p1b=z->noab();p1b<z->noab()+z->nvab();++p1b) { 
  long tileoffset; 
  tileoffset=(p1b-z->noab()+z->nvab()*(h2b)); 
  if (in[1]->is_this_local(tileoffset)) { 
   if (!z->restricted() || z->get_spin(h2b)+z->get_spin(p1b)!=4L) { 
    if (z->get_spin(h2b)==z->get_spin(p1b)) { 
     if ((z->get_sym(h2b)^z->get_sym(p1b))==(z->irrep_y()^z->irrep_e())) { 
      long dimc=z->get_range(h2b)*z->get_range(p1b); 
      double* k_c_sort=z->mem()->malloc_local_double(dimc); 
      std::fill(k_c_sort,k_c_sort+(size_t)dimc,0.0); 
      for (long h3b=0L;h3b<z->noab();++h3b) { 
       for (long h4b=0L;h4b<z->noab();++h4b) { 
        for (long h5b=h4b;h5b<z->noab();++h5b) { 
         if (z->get_spin(h2b)+z->get_spin(h3b)==z->get_spin(h4b)+z->get_spin(h5b)) { 
          if ((z->get_sym(h2b)^(z->get_sym(h3b)^(z->get_sym(h4b)^z->get_sym(h5b))))==z->irrep_y()) { 
           long h2b_0,h3b_0,h4b_0,h5b_0; 
           z->restricted_4(h2b,h3b,h4b,h5b,h2b_0,h3b_0,h4b_0,h5b_0); 
           long h4b_1,h5b_1,h3b_1,p1b_1; 
           z->restricted_4(h4b,h5b,h3b,p1b,h4b_1,h5b_1,h3b_1,p1b_1); 
           long dim_common=z->get_range(h3b)*z->get_range(h4b)*z->get_range(h5b); 
           long dima0_sort=z->get_range(h2b); 
           long dima0=dim_common*dima0_sort; 
           long dima1_sort=z->get_range(p1b); 
           long dima1=dim_common*dima1_sort; 
           if (dima0>0L && dima1>0L) { 
            double* k_a0_sort=z->mem()->malloc_local_double(dima0); 
            double* k_a0=z->mem()->malloc_local_double(dima0); 
            if (h2b<h3b) { 
             z->glambda2()->get_block(h5b_0+z->noab()*(h4b_0+z->noab()*(h3b_0+z->noab()*(h2b_0))),k_a0); 
             z->sort_indices4(k_a0,k_a0_sort,z->get_range(h2b),z->get_range(h3b),z->get_range(h4b),z->get_range(h5b),0,3,2,1,+1.0,false); 
            } 
            else if (h3b<=h2b) { 
             z->glambda2()->get_block(h5b_0+z->noab()*(h4b_0+z->noab()*(h2b_0+z->noab()*(h3b_0))),k_a0); 
             z->sort_indices4(k_a0,k_a0_sort,z->get_range(h3b),z->get_range(h2b),z->get_range(h4b),z->get_range(h5b),1,3,2,0,-1.0,false); 
            } 
            z->mem()->free_local_double(k_a0); 
            double* k_a1_sort=z->mem()->malloc_local_double(dima1); 
            double* k_a1=z->mem()->malloc_local_double(dima1); 
            z->vd2()->get_block(p1b_1+(z->nab())*(h3b_1+(z->nab())*(h5b_1+z->noab()*(h4b_1))),k_a1); 
            z->sort_indices4(k_a1,k_a1_sort,z->get_range(h4b),z->get_range(h5b),z->get_range(h3b),z->get_range(p1b),3,1,0,2,+1.0,false); 
            z->mem()->free_local_double(k_a1); 
            double factor=1.0; 
            if (h4b==h5b) { 
             factor=factor/2.0; 
            } 
            z->smith_dgemm(dima0_sort,dima1_sort,dim_common,factor,k_a0_sort,dim_common,k_a1_sort,dim_common,1.0,k_c_sort,dima0_sort); 
            z->mem()->free_local_double(k_a1_sort); 
            z->mem()->free_local_double(k_a0_sort); 
           } 
          } 
         } 
        } 
       } 
      } 
      double* k_c=z->mem()->malloc_local_double(dimc); 
      z->sort_indices2(k_c_sort,k_c,z->get_range(p1b),z->get_range(h2b),1,0,-0.5/0.5,false); 
      in[1]->add_block(p1b-z->noab()+z->nvab()*(h2b),k_c); 
      z->mem()->free_local_double(k_c); 
      z->mem()->free_local_double(k_c_sort); 
     } 
    } 
   } 
  } 
 } 
} 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::smith_1_8(){ 
      
for (long h2b=0L;h2b<z->noab();++h2b) { 
 for (long p1b=z->noab();p1b<z->noab()+z->nvab();++p1b) { 
  long tileoffset; 
  tileoffset=(p1b-z->noab()+z->nvab()*(h2b)); 
  if (in[1]->is_this_local(tileoffset)) { 
   if (!z->restricted() || z->get_spin(h2b)+z->get_spin(p1b)!=4L) { 
    if (z->get_spin(h2b)==z->get_spin(p1b)) { 
     if ((z->get_sym(h2b)^z->get_sym(p1b))==(z->irrep_e()^(z->irrep_t()^z->irrep_y()))) { 
      long dimc=z->get_range(h2b)*z->get_range(p1b); 
      double* k_c_sort=z->mem()->malloc_local_double(dimc); 
      std::fill(k_c_sort,k_c_sort+(size_t)dimc,0.0); 
      for (long h3b=0L;h3b<z->noab();++h3b) { 
       for (long h4b=h3b;h4b<z->noab();++h4b) { 
        for (long p5b=z->noab();p5b<z->noab()+z->nvab();++p5b) { 
         if (z->get_spin(h3b)+z->get_spin(h4b)==z->get_spin(p1b)+z->get_spin(p5b)) { 
          if ((z->get_sym(h3b)^(z->get_sym(h4b)^(z->get_sym(p1b)^z->get_sym(p5b))))==z->irrep_e()) { 
           long h3b_0,h4b_0,p1b_0,p5b_0; 
           z->restricted_4(h3b,h4b,p1b,p5b,h3b_0,h4b_0,p1b_0,p5b_0); 
           long h2b_1,p5b_1,h3b_1,h4b_1; 
           z->restricted_4(h2b,p5b,h3b,h4b,h2b_1,p5b_1,h3b_1,h4b_1); 
           long dim_common=z->get_range(h3b)*z->get_range(h4b)*z->get_range(p5b); 
           long dima0_sort=z->get_range(p1b); 
           long dima0=dim_common*dima0_sort; 
           long dima1_sort=z->get_range(h2b); 
           long dima1=dim_common*dima1_sort; 
           if (dima0>0L && dima1>0L) { 
            double* k_a0_sort=z->mem()->malloc_local_double(dima0); 
            double* k_a0=z->mem()->malloc_local_double(dima0); 
            if (p1b<p5b) { 
             z->vd2()->get_block(p5b_0+(z->nab())*(p1b_0+(z->nab())*(h4b_0+z->noab()*(h3b_0))),k_a0); 
             z->sort_indices4(k_a0,k_a0_sort,z->get_range(h3b),z->get_range(h4b),z->get_range(p1b),z->get_range(p5b),2,3,1,0,+1.0,false); 
            } 
            else if (p5b<=p1b) { 
             z->vd2()->get_block(p1b_0+(z->nab())*(p5b_0+(z->nab())*(h4b_0+z->noab()*(h3b_0))),k_a0); 
             z->sort_indices4(k_a0,k_a0_sort,z->get_range(h3b),z->get_range(h4b),z->get_range(p5b),z->get_range(p1b),3,2,1,0,-1.0,false); 
            } 
            z->mem()->free_local_double(k_a0); 
            double* k_a1_sort=z->mem()->malloc_local_double(dima1); 
            double* k_a1=z->mem()->malloc_local_double(dima1); 
            in[2]->get_block(h4b_1+z->noab()*(h3b_1+z->noab()*(p5b_1-z->noab()+z->nvab()*(h2b_1))),k_a1); 
            z->sort_indices4(k_a1,k_a1_sort,z->get_range(h2b),z->get_range(p5b),z->get_range(h3b),z->get_range(h4b),0,1,3,2,+1.0,false); 
            z->mem()->free_local_double(k_a1); 
            double factor=1.0; 
            if (h3b==h4b) { 
             factor=factor/2.0; 
            } 
            z->smith_dgemm(dima0_sort,dima1_sort,dim_common,factor,k_a0_sort,dim_common,k_a1_sort,dim_common,1.0,k_c_sort,dima0_sort); 
            z->mem()->free_local_double(k_a1_sort); 
            z->mem()->free_local_double(k_a0_sort); 
           } 
          } 
         } 
        } 
       } 
      } 
      double* k_c=z->mem()->malloc_local_double(dimc); 
      z->sort_indices2(k_c_sort,k_c,z->get_range(h2b),z->get_range(p1b),0,1,+0.5/0.5,false); 
      in[1]->add_block(p1b-z->noab()+z->nvab()*(h2b),k_c); 
      z->mem()->free_local_double(k_c); 
      z->mem()->free_local_double(k_c_sort); 
     } 
    } 
   } 
  } 
 } 
} 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::offset_smith_1_8(){ 
 
long size=0L; 
for (long h2b=0L;h2b<z->noab();++h2b) { 
 for (long p5b=z->noab();p5b<z->noab()+z->nvab();++p5b) { 
  for (long h3b=0L;h3b<z->noab();++h3b) { 
   for (long h4b=h3b;h4b<z->noab();++h4b) { 
    if (z->get_spin(h2b)+z->get_spin(p5b)==z->get_spin(h3b)+z->get_spin(h4b)) { 
     if ((z->get_sym(h2b)^(z->get_sym(p5b)^(z->get_sym(h3b)^z->get_sym(h4b))))==(z->irrep_t()^z->irrep_y())) { 
      if (!z->restricted() || z->get_spin(h2b)+z->get_spin(p5b)+z->get_spin(h3b)+z->get_spin(h4b)!=8L) { 
       in[2]->input_offset(h4b+z->noab()*(h3b+z->noab()*(p5b-z->noab()+z->nvab()*(h2b))),size); 
       size+=z->get_range(h2b)*z->get_range(p5b)*z->get_range(h3b)*z->get_range(h4b); 
      } 
     } 
    } 
   } 
  } 
 } 
} 
in[2]->set_filesize(size); 
in[2]->createfile(); 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::smith_1_9(){ 
      
for (long h3b=0L;h3b<z->noab();++h3b) { 
 for (long h4b=0L;h4b<z->noab();++h4b) { 
  for (long p1b=z->noab();p1b<z->noab()+z->nvab();++p1b) { 
   for (long p2b=z->noab();p2b<z->noab()+z->nvab();++p2b) { 
    long tileoffset; 
    if (h3b<h4b && p1b<p2b) { 
     tileoffset=(p2b-z->noab()+z->nvab()*(p1b-z->noab()+z->nvab()*(h4b+z->noab()*(h3b)))); 
    } 
    else if (h3b<h4b && p2b<=p1b) { 
     tileoffset=(p1b-z->noab()+z->nvab()*(p2b-z->noab()+z->nvab()*(h4b+z->noab()*(h3b)))); 
    } 
    else if (h4b<=h3b && p1b<p2b) { 
     tileoffset=(p2b-z->noab()+z->nvab()*(p1b-z->noab()+z->nvab()*(h3b+z->noab()*(h4b)))); 
    } 
    else if (h4b<=h3b && p2b<=p1b) { 
     tileoffset=(p1b-z->noab()+z->nvab()*(p2b-z->noab()+z->nvab()*(h3b+z->noab()*(h4b)))); 
    } 
    if (in[1]->is_this_local(tileoffset)) { 
     if (!z->restricted() || z->get_spin(h3b)+z->get_spin(h4b)+z->get_spin(p1b)+z->get_spin(p2b)!=8L) { 
      if (z->get_spin(h3b)+z->get_spin(h4b)==z->get_spin(p1b)+z->get_spin(p2b)) { 
       if ((z->get_sym(h3b)^(z->get_sym(h4b)^(z->get_sym(p1b)^z->get_sym(p2b))))==(z->irrep_y()^z->irrep_v())) { 
        long dimc=z->get_range(h3b)*z->get_range(h4b)*z->get_range(p1b)*z->get_range(p2b); 
        double* k_c_sort=z->mem()->malloc_local_double(dimc); 
        std::fill(k_c_sort,k_c_sort+(size_t)dimc,0.0); 
        for (long h5b=0L;h5b<z->noab();++h5b) { 
         for (long q6b=z->noab()+z->nvab();q6b<z->nab();++q6b) { 
          if (z->get_spin(h3b)+z->get_spin(h5b)==z->get_spin(p1b)+z->get_spin(q6b)) { 
           if ((z->get_sym(h3b)^(z->get_sym(h5b)^(z->get_sym(p1b)^z->get_sym(q6b))))==z->irrep_y()) { 
            long h3b_0,h5b_0,p1b_0,q6b_0; 
            z->restricted_4(h3b,h5b,p1b,q6b,h3b_0,h5b_0,p1b_0,q6b_0); 
            long h4b_1,q6b_1,h5b_1,p2b_1; 
            z->restricted_4(h4b,q6b,h5b,p2b,h4b_1,q6b_1,h5b_1,p2b_1); 
            long dim_common=z->get_range(h5b)*z->get_range(q6b); 
            long dima0_sort=z->get_range(h3b)*z->get_range(p1b); 
            long dima0=dim_common*dima0_sort; 
            long dima1_sort=z->get_range(h4b)*z->get_range(p2b); 
            long dima1=dim_common*dima1_sort; 
            if (dima0>0L && dima1>0L) { 
             double* k_a0_sort=z->mem()->malloc_local_double(dima0); 
             double* k_a0=z->mem()->malloc_local_double(dima0); 
             if (h3b<h5b) { 
              z->ly()->get_block(q6b_0-z->noab()-z->nvab()+z->ncab()*(p1b_0-z->noab()+z->nvab()*(h5b_0+z->noab()*(h3b_0))),k_a0); 
              z->sort_indices4(k_a0,k_a0_sort,z->get_range(h3b),z->get_range(h5b),z->get_range(p1b),z->get_range(q6b),2,0,3,1,+1.0,false); 
             } 
             else if (h5b<=h3b) { 
              z->ly()->get_block(q6b_0-z->noab()-z->nvab()+z->ncab()*(p1b_0-z->noab()+z->nvab()*(h3b_0+z->noab()*(h5b_0))),k_a0); 
              z->sort_indices4(k_a0,k_a0_sort,z->get_range(h5b),z->get_range(h3b),z->get_range(p1b),z->get_range(q6b),2,1,3,0,-1.0,false); 
             } 
             z->mem()->free_local_double(k_a0); 
             double* k_a1_sort=z->mem()->malloc_local_double(dima1); 
             double* k_a1=z->mem()->malloc_local_double(dima1); 
             z->v2()->get_block(p2b_1+(z->nab())*(h5b_1+(z->nab())*(q6b_1+(z->nab())*(h4b_1))),k_a1); 
             z->sort_indices4(k_a1,k_a1_sort,z->get_range(h4b),z->get_range(q6b),z->get_range(h5b),z->get_range(p2b),3,0,1,2,+1.0,false); 
             z->mem()->free_local_double(k_a1); 
             double factor=1.0; 
             z->smith_dgemm(dima0_sort,dima1_sort,dim_common,factor,k_a0_sort,dim_common,k_a1_sort,dim_common,1.0,k_c_sort,dima0_sort); 
             z->mem()->free_local_double(k_a1_sort); 
             z->mem()->free_local_double(k_a0_sort); 
            } 
           } 
          } 
         } 
        } 
        double* k_c=z->mem()->malloc_local_double(dimc); 
        if (h4b>=h3b && p2b>=p1b) { 
         z->sort_indices4(k_c_sort,k_c,z->get_range(p2b),z->get_range(h4b),z->get_range(p1b),z->get_range(h3b),3,1,2,0,-1.0,false); 
         in[1]->add_block(p2b-z->noab()+z->nvab()*(p1b-z->noab()+z->nvab()*(h4b+z->noab()*(h3b))),k_c); 
        } 
        if (h4b>=h3b && p1b>=p2b) { 
         z->sort_indices4(k_c_sort,k_c,z->get_range(p2b),z->get_range(h4b),z->get_range(p1b),z->get_range(h3b),3,1,0,2,+1.0,false); 
         in[1]->add_block(p1b-z->noab()+z->nvab()*(p2b-z->noab()+z->nvab()*(h4b+z->noab()*(h3b))),k_c); 
        } 
        if (h3b>=h4b && p2b>=p1b) { 
         z->sort_indices4(k_c_sort,k_c,z->get_range(p2b),z->get_range(h4b),z->get_range(p1b),z->get_range(h3b),1,3,2,0,+1.0,false); 
         in[1]->add_block(p2b-z->noab()+z->nvab()*(p1b-z->noab()+z->nvab()*(h3b+z->noab()*(h4b))),k_c); 
        } 
        if (h3b>=h4b && p1b>=p2b) { 
         z->sort_indices4(k_c_sort,k_c,z->get_range(p2b),z->get_range(h4b),z->get_range(p1b),z->get_range(h3b),1,3,0,2,-1.0,false); 
         in[1]->add_block(p1b-z->noab()+z->nvab()*(p2b-z->noab()+z->nvab()*(h3b+z->noab()*(h4b))),k_c); 
        } 
        z->mem()->free_local_double(k_c); 
        z->mem()->free_local_double(k_c_sort); 
       } 
      } 
     } 
    } 
   } 
  } 
 } 
} 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::smith_2_13(){ 
      
for (long h2b=0L;h2b<z->noab();++h2b) { 
 for (long p5b=z->noab();p5b<z->noab()+z->nvab();++p5b) { 
  for (long h3b=0L;h3b<z->noab();++h3b) { 
   for (long q4b=z->noab()+z->nvab();q4b<z->nab();++q4b) { 
    long tileoffset; 
    tileoffset=(q4b-z->noab()-z->nvab()+z->ncab()*(h3b+z->noab()*(p5b-z->noab()+z->nvab()*(h2b)))); 
    if (in[2]->is_this_local(tileoffset)) { 
     if (!z->restricted() || z->get_spin(h2b)+z->get_spin(p5b)+z->get_spin(h3b)+z->get_spin(q4b)!=8L) { 
      if (z->get_spin(h2b)+z->get_spin(p5b)==z->get_spin(h3b)+z->get_spin(q4b)) { 
       if ((z->get_sym(h2b)^(z->get_sym(p5b)^(z->get_sym(h3b)^z->get_sym(q4b))))==(z->irrep_t()^z->irrep_y())) { 
        long dimc=z->get_range(h2b)*z->get_range(p5b)*z->get_range(h3b)*z->get_range(q4b); 
        double* k_c_sort=z->mem()->malloc_local_double(dimc); 
        std::fill(k_c_sort,k_c_sort+(size_t)dimc,0.0); 
        for (long h7b=0L;h7b<z->noab();++h7b) { 
         for (long p6b=z->noab();p6b<z->noab()+z->nvab();++p6b) { 
          if (z->get_spin(p5b)+z->get_spin(p6b)==z->get_spin(h3b)+z->get_spin(h7b)) { 
           if ((z->get_sym(p5b)^(z->get_sym(p6b)^(z->get_sym(h3b)^z->get_sym(h7b))))==z->irrep_t()) { 
            long p5b_0,p6b_0,h3b_0,h7b_0; 
            z->restricted_4(p5b,p6b,h3b,h7b,p5b_0,p6b_0,h3b_0,h7b_0); 
            long h2b_1,h7b_1,p6b_1,q4b_1; 
            z->restricted_4(h2b,h7b,p6b,q4b,h2b_1,h7b_1,p6b_1,q4b_1); 
            long dim_common=z->get_range(h7b)*z->get_range(p6b); 
            long dima0_sort=z->get_range(p5b)*z->get_range(h3b); 
            long dima0=dim_common*dima0_sort; 
            long dima1_sort=z->get_range(h2b)*z->get_range(q4b); 
            long dima1=dim_common*dima1_sort; 
            if (dima0>0L && dima1>0L) { 
             double* k_a0_sort=z->mem()->malloc_local_double(dima0); 
             double* k_a0=z->mem()->malloc_local_double(dima0); 
             if (p5b<p6b && h3b<h7b) { 
              z->t2()->get_block(h7b_0+z->noab()*(h3b_0+z->noab()*(p6b_0-z->noab()+z->nvab()*(p5b_0-z->noab()))),k_a0); 
              z->sort_indices4(k_a0,k_a0_sort,z->get_range(p5b),z->get_range(p6b),z->get_range(h3b),z->get_range(h7b),2,0,1,3,+1.0,false); 
             } 
             else if (p5b<p6b && h7b<=h3b) { 
              z->t2()->get_block(h3b_0+z->noab()*(h7b_0+z->noab()*(p6b_0-z->noab()+z->nvab()*(p5b_0-z->noab()))),k_a0); 
              z->sort_indices4(k_a0,k_a0_sort,z->get_range(p5b),z->get_range(p6b),z->get_range(h7b),z->get_range(h3b),3,0,1,2,-1.0,false); 
             } 
             else if (p6b<=p5b && h3b<h7b) { 
              z->t2()->get_block(h7b_0+z->noab()*(h3b_0+z->noab()*(p5b_0-z->noab()+z->nvab()*(p6b_0-z->noab()))),k_a0); 
              z->sort_indices4(k_a0,k_a0_sort,z->get_range(p6b),z->get_range(p5b),z->get_range(h3b),z->get_range(h7b),2,1,0,3,-1.0,false); 
             } 
             else if (p6b<=p5b && h7b<=h3b) { 
              z->t2()->get_block(h3b_0+z->noab()*(h7b_0+z->noab()*(p5b_0-z->noab()+z->nvab()*(p6b_0-z->noab()))),k_a0); 
              z->sort_indices4(k_a0,k_a0_sort,z->get_range(p6b),z->get_range(p5b),z->get_range(h7b),z->get_range(h3b),3,1,0,2,+1.0,false); 
             } 
             z->mem()->free_local_double(k_a0); 
             double* k_a1_sort=z->mem()->malloc_local_double(dima1); 
             double* k_a1=z->mem()->malloc_local_double(dima1); 
             if (h2b<h7b) { 
              z->ly()->get_block(q4b_1-z->noab()-z->nvab()+z->ncab()*(p6b_1-z->noab()+z->nvab()*(h7b_1+z->noab()*(h2b_1))),k_a1); 
              z->sort_indices4(k_a1,k_a1_sort,z->get_range(h2b),z->get_range(h7b),z->get_range(p6b),z->get_range(q4b),3,0,2,1,+1.0,false); 
             } 
             else if (h7b<=h2b) { 
              z->ly()->get_block(q4b_1-z->noab()-z->nvab()+z->ncab()*(p6b_1-z->noab()+z->nvab()*(h2b_1+z->noab()*(h7b_1))),k_a1); 
              z->sort_indices4(k_a1,k_a1_sort,z->get_range(h7b),z->get_range(h2b),z->get_range(p6b),z->get_range(q4b),3,1,2,0,-1.0,false); 
             } 
             z->mem()->free_local_double(k_a1); 
             double factor=1.0; 
             z->smith_dgemm(dima0_sort,dima1_sort,dim_common,factor,k_a0_sort,dim_common,k_a1_sort,dim_common,1.0,k_c_sort,dima0_sort); 
             z->mem()->free_local_double(k_a1_sort); 
             z->mem()->free_local_double(k_a0_sort); 
            } 
           } 
          } 
         } 
        } 
        double* k_c=z->mem()->malloc_local_double(dimc); 
        z->sort_indices4(k_c_sort,k_c,z->get_range(q4b),z->get_range(h2b),z->get_range(h3b),z->get_range(p5b),1,3,2,0,+1.0,false); 
        in[2]->add_block(q4b-z->noab()-z->nvab()+z->ncab()*(h3b+z->noab()*(p5b-z->noab()+z->nvab()*(h2b))),k_c); 
        z->mem()->free_local_double(k_c); 
        z->mem()->free_local_double(k_c_sort); 
       } 
      } 
     } 
    } 
   } 
  } 
 } 
} 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::smith_2_14(){ 
      
for (long h2b=0L;h2b<z->noab();++h2b) { 
 for (long q5b=z->noab()+z->nvab();q5b<z->nab();++q5b) { 
  for (long h3b=0L;h3b<z->noab();++h3b) { 
   for (long h4b=h3b;h4b<z->noab();++h4b) { 
    long tileoffset; 
    tileoffset=(h4b+z->noab()*(h3b+z->noab()*(q5b-z->noab()-z->nvab()+z->ncab()*(h2b)))); 
    if (in[2]->is_this_local(tileoffset)) { 
     if (!z->restricted() || z->get_spin(h2b)+z->get_spin(q5b)+z->get_spin(h3b)+z->get_spin(h4b)!=8L) { 
      if (z->get_spin(h2b)+z->get_spin(q5b)==z->get_spin(h3b)+z->get_spin(h4b)) { 
       if ((z->get_sym(h2b)^(z->get_sym(q5b)^(z->get_sym(h3b)^z->get_sym(h4b))))==(z->irrep_t()^z->irrep_v())) { 
        long dimc=z->get_range(h2b)*z->get_range(q5b)*z->get_range(h3b)*z->get_range(h4b); 
        double* k_c_sort=z->mem()->malloc_local_double(dimc); 
        std::fill(k_c_sort,k_c_sort+(size_t)dimc,0.0); 
        for (long p6b=z->noab();p6b<z->noab()+z->nvab();++p6b) { 
         for (long p7b=p6b;p7b<z->noab()+z->nvab();++p7b) { 
          if (z->get_spin(p6b)+z->get_spin(p7b)==z->get_spin(h3b)+z->get_spin(h4b)) { 
           if ((z->get_sym(p6b)^(z->get_sym(p7b)^(z->get_sym(h3b)^z->get_sym(h4b))))==z->irrep_t()) { 
            long p6b_0,p7b_0,h3b_0,h4b_0; 
            z->restricted_4(p6b,p7b,h3b,h4b,p6b_0,p7b_0,h3b_0,h4b_0); 
            long h2b_1,q5b_1,p6b_1,p7b_1; 
            z->restricted_4(h2b,q5b,p6b,p7b,h2b_1,q5b_1,p6b_1,p7b_1); 
            long dim_common=z->get_range(p6b)*z->get_range(p7b); 
            long dima0_sort=z->get_range(h3b)*z->get_range(h4b); 
            long dima0=dim_common*dima0_sort; 
            long dima1_sort=z->get_range(h2b)*z->get_range(q5b); 
            long dima1=dim_common*dima1_sort; 
            if (dima0>0L && dima1>0L) { 
             double* k_a0_sort=z->mem()->malloc_local_double(dima0); 
             double* k_a0=z->mem()->malloc_local_double(dima0); 
             z->t2()->get_block(h4b_0+z->noab()*(h3b_0+z->noab()*(p7b_0-z->noab()+z->nvab()*(p6b_0-z->noab()))),k_a0); 
             z->sort_indices4(k_a0,k_a0_sort,z->get_range(p6b),z->get_range(p7b),z->get_range(h3b),z->get_range(h4b),3,2,1,0,+1.0,false); 
             z->mem()->free_local_double(k_a0); 
             double* k_a1_sort=z->mem()->malloc_local_double(dima1); 
             double* k_a1=z->mem()->malloc_local_double(dima1); 
             z->v2()->get_block(p7b_1+(z->nab())*(p6b_1+(z->nab())*(q5b_1+(z->nab())*(h2b_1))),k_a1); 
             z->sort_indices4(k_a1,k_a1_sort,z->get_range(h2b),z->get_range(q5b),z->get_range(p6b),z->get_range(p7b),1,0,3,2,+1.0,false); 
             z->mem()->free_local_double(k_a1); 
             double factor=1.0; 
             if (p6b==p7b) { 
              factor=factor/2.0; 
             } 
             z->smith_dgemm(dima0_sort,dima1_sort,dim_common,factor,k_a0_sort,dim_common,k_a1_sort,dim_common,1.0,k_c_sort,dima0_sort); 
             z->mem()->free_local_double(k_a1_sort); 
             z->mem()->free_local_double(k_a0_sort); 
            } 
           } 
          } 
         } 
        } 
        double* k_c=z->mem()->malloc_local_double(dimc); 
        z->sort_indices4(k_c_sort,k_c,z->get_range(q5b),z->get_range(h2b),z->get_range(h4b),z->get_range(h3b),1,0,3,2,-0.5/0.5,false); 
        in[2]->add_block(h4b+z->noab()*(h3b+z->noab()*(q5b-z->noab()-z->nvab()+z->ncab()*(h2b))),k_c); 
        z->mem()->free_local_double(k_c); 
        z->mem()->free_local_double(k_c_sort); 
       } 
      } 
     } 
    } 
   } 
  } 
 } 
} 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::smith_2_2(){ 
      
for (long h2b=0L;h2b<z->noab();++h2b) { 
 for (long h5b=h2b;h5b<z->noab();++h5b) { 
  for (long h3b=0L;h3b<z->noab();++h3b) { 
   for (long h4b=h3b;h4b<z->noab();++h4b) { 
    long tileoffset; 
    tileoffset=(h4b+z->noab()*(h3b+z->noab()*(h5b+z->noab()*(h2b)))); 
    if (in[2]->is_this_local(tileoffset)) { 
     if (!z->restricted() || z->get_spin(h2b)+z->get_spin(h5b)+z->get_spin(h3b)+z->get_spin(h4b)!=8L) { 
      if (z->get_spin(h2b)+z->get_spin(h5b)==z->get_spin(h3b)+z->get_spin(h4b)) { 
       if ((z->get_sym(h2b)^(z->get_sym(h5b)^(z->get_sym(h3b)^z->get_sym(h4b))))==(z->irrep_y()^z->irrep_e())) { 
        long dimc=z->get_range(h2b)*z->get_range(h5b)*z->get_range(h3b)*z->get_range(h4b); 
        double* k_c_sort=z->mem()->malloc_local_double(dimc); 
        std::fill(k_c_sort,k_c_sort+(size_t)dimc,0.0); 
        for (long h6b=0L;h6b<z->noab();++h6b) { 
         for (long h7b=h6b;h7b<z->noab();++h7b) { 
          if (z->get_spin(h2b)+z->get_spin(h5b)==z->get_spin(h6b)+z->get_spin(h7b)) { 
           if ((z->get_sym(h2b)^(z->get_sym(h5b)^(z->get_sym(h6b)^z->get_sym(h7b))))==z->irrep_y()) { 
            long h2b_0,h5b_0,h6b_0,h7b_0; 
            z->restricted_4(h2b,h5b,h6b,h7b,h2b_0,h5b_0,h6b_0,h7b_0); 
            long h6b_1,h7b_1,h3b_1,h4b_1; 
            z->restricted_4(h6b,h7b,h3b,h4b,h6b_1,h7b_1,h3b_1,h4b_1); 
            long dim_common=z->get_range(h6b)*z->get_range(h7b); 
            long dima0_sort=z->get_range(h2b)*z->get_range(h5b); 
            long dima0=dim_common*dima0_sort; 
            long dima1_sort=z->get_range(h3b)*z->get_range(h4b); 
            long dima1=dim_common*dima1_sort; 
            if (dima0>0L && dima1>0L) { 
             double* k_a0_sort=z->mem()->malloc_local_double(dima0); 
             double* k_a0=z->mem()->malloc_local_double(dima0); 
             z->glambda2()->get_block(h7b_0+z->noab()*(h6b_0+z->noab()*(h5b_0+z->noab()*(h2b_0))),k_a0); 
             z->sort_indices4(k_a0,k_a0_sort,z->get_range(h2b),z->get_range(h5b),z->get_range(h6b),z->get_range(h7b),1,0,3,2,+1.0,false); 
             z->mem()->free_local_double(k_a0); 
             double* k_a1_sort=z->mem()->malloc_local_double(dima1); 
             double* k_a1=z->mem()->malloc_local_double(dima1); 
             z->xs2()->get_block(h4b_1+z->noab()*(h3b_1+z->noab()*(h7b_1+z->noab()*(h6b_1))),k_a1); 
             z->sort_indices4(k_a1,k_a1_sort,z->get_range(h6b),z->get_range(h7b),z->get_range(h3b),z->get_range(h4b),3,2,1,0,+1.0,false); 
             z->mem()->free_local_double(k_a1); 
             double factor=1.0; 
             if (h6b==h7b) { 
              factor=factor/2.0; 
             } 
             z->smith_dgemm(dima0_sort,dima1_sort,dim_common,factor,k_a0_sort,dim_common,k_a1_sort,dim_common,1.0,k_c_sort,dima0_sort); 
             z->mem()->free_local_double(k_a1_sort); 
             z->mem()->free_local_double(k_a0_sort); 
            } 
           } 
          } 
         } 
        } 
        double* k_c=z->mem()->malloc_local_double(dimc); 
        z->sort_indices4(k_c_sort,k_c,z->get_range(h4b),z->get_range(h3b),z->get_range(h5b),z->get_range(h2b),3,2,1,0,-0.5/0.5,false); 
        in[2]->add_block(h4b+z->noab()*(h3b+z->noab()*(h5b+z->noab()*(h2b))),k_c); 
        z->mem()->free_local_double(k_c); 
        z->mem()->free_local_double(k_c_sort); 
       } 
      } 
     } 
    } 
   } 
  } 
 } 
} 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::smith_2_7(){ 
      
for (long h2b=0L;h2b<z->noab();++h2b) { 
 for (long q5b=z->noab()+z->nvab();q5b<z->nab();++q5b) { 
  for (long h3b=0L;h3b<z->noab();++h3b) { 
   for (long h4b=0L;h4b<z->noab();++h4b) { 
    long tileoffset; 
    if (h3b<h4b) { 
     tileoffset=(h4b+z->noab()*(h3b+z->noab()*(q5b-z->noab()-z->nvab()+z->ncab()*(h2b)))); 
    } 
    else if (h4b<=h3b) { 
     tileoffset=(h3b+z->noab()*(h4b+z->noab()*(q5b-z->noab()-z->nvab()+z->ncab()*(h2b)))); 
    } 
    if (in[2]->is_this_local(tileoffset)) { 
     if (!z->restricted() || z->get_spin(h2b)+z->get_spin(q5b)+z->get_spin(h3b)+z->get_spin(h4b)!=8L) { 
      if (z->get_spin(h2b)+z->get_spin(q5b)==z->get_spin(h3b)+z->get_spin(h4b)) { 
       if ((z->get_sym(h2b)^(z->get_sym(q5b)^(z->get_sym(h3b)^z->get_sym(h4b))))==(z->irrep_t()^z->irrep_v())) { 
        long dimc=z->get_range(h2b)*z->get_range(q5b)*z->get_range(h3b)*z->get_range(h4b); 
        double* k_c_sort=z->mem()->malloc_local_double(dimc); 
        std::fill(k_c_sort,k_c_sort+(size_t)dimc,0.0); 
        for (long p6b=z->noab();p6b<z->noab()+z->nvab();++p6b) { 
         if (z->get_spin(p6b)==z->get_spin(h3b)) { 
          if ((z->get_sym(p6b)^z->get_sym(h3b))==z->irrep_t()) { 
           long p6b_0,h3b_0; 
           z->restricted_2(p6b,h3b,p6b_0,h3b_0); 
           long h2b_1,q5b_1,h4b_1,p6b_1; 
           z->restricted_4(h2b,q5b,h4b,p6b,h2b_1,q5b_1,h4b_1,p6b_1); 
           long dim_common=z->get_range(p6b); 
           long dima0_sort=z->get_range(h3b); 
           long dima0=dim_common*dima0_sort; 
           long dima1_sort=z->get_range(h2b)*z->get_range(q5b)*z->get_range(h4b); 
           long dima1=dim_common*dima1_sort; 
           if (dima0>0L && dima1>0L) { 
            double* k_a0_sort=z->mem()->malloc_local_double(dima0); 
            double* k_a0=z->mem()->malloc_local_double(dima0); 
            z->t1()->get_block(h3b_0+z->noab()*(p6b_0-z->noab()),k_a0); 
            z->sort_indices2(k_a0,k_a0_sort,z->get_range(p6b),z->get_range(h3b),1,0,+1.0,false); 
            z->mem()->free_local_double(k_a0); 
            double* k_a1_sort=z->mem()->malloc_local_double(dima1); 
            double* k_a1=z->mem()->malloc_local_double(dima1); 
            in[3]->get_block(p6b_1-z->noab()+z->nvab()*(h4b_1+z->noab()*(q5b_1-z->noab()-z->nvab()+z->ncab()*(h2b_1))),k_a1); 
            z->sort_indices4(k_a1,k_a1_sort,z->get_range(h2b),z->get_range(q5b),z->get_range(h4b),z->get_range(p6b),2,1,0,3,+1.0,false); 
            z->mem()->free_local_double(k_a1); 
            double factor=1.0; 
            z->smith_dgemm(dima0_sort,dima1_sort,dim_common,factor,k_a0_sort,dim_common,k_a1_sort,dim_common,1.0,k_c_sort,dima0_sort); 
            z->mem()->free_local_double(k_a1_sort); 
            z->mem()->free_local_double(k_a0_sort); 
           } 
          } 
         } 
        } 
        double* k_c=z->mem()->malloc_local_double(dimc); 
        if (h4b>=h3b) { 
         z->sort_indices4(k_c_sort,k_c,z->get_range(h4b),z->get_range(q5b),z->get_range(h2b),z->get_range(h3b),2,1,3,0,+1.0,false); 
         in[2]->add_block(h4b+z->noab()*(h3b+z->noab()*(q5b-z->noab()-z->nvab()+z->ncab()*(h2b))),k_c); 
        } 
        if (h3b>=h4b) { 
         z->sort_indices4(k_c_sort,k_c,z->get_range(h4b),z->get_range(q5b),z->get_range(h2b),z->get_range(h3b),2,1,0,3,-1.0,false); 
         in[2]->add_block(h3b+z->noab()*(h4b+z->noab()*(q5b-z->noab()-z->nvab()+z->ncab()*(h2b))),k_c); 
        } 
        z->mem()->free_local_double(k_c); 
        z->mem()->free_local_double(k_c_sort); 
       } 
      } 
     } 
    } 
   } 
  } 
 } 
} 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::smith_2_7_0(){ 
      
for (long h2b=0L;h2b<z->noab();++h2b) { 
 for (long q5b=z->noab()+z->nvab();q5b<z->nab();++q5b) { 
  for (long h4b=0L;h4b<z->noab();++h4b) { 
   for (long p6b=z->noab();p6b<z->noab()+z->nvab();++p6b) { 
    long tileoffset; 
    tileoffset=(p6b-z->noab()+z->nvab()*(h4b+z->noab()*(q5b-z->noab()-z->nvab()+z->ncab()*(h2b)))); 
    if (in[3]->is_this_local(tileoffset)) { 
     if (!z->restricted() || z->get_spin(h2b)+z->get_spin(q5b)+z->get_spin(h4b)+z->get_spin(p6b)!=8L) { 
      if (z->get_spin(h2b)+z->get_spin(q5b)==z->get_spin(h4b)+z->get_spin(p6b)) { 
       if ((z->get_sym(h2b)^(z->get_sym(q5b)^(z->get_sym(h4b)^z->get_sym(p6b))))==z->irrep_v()) { 
        long dimc=z->get_range(h2b)*z->get_range(q5b)*z->get_range(h4b)*z->get_range(p6b); 
        long h2b_0,q5b_0,h4b_0,p6b_0; 
        z->restricted_4(h2b,q5b,h4b,p6b,h2b_0,q5b_0,h4b_0,p6b_0); 
        long dim_common=1L; 
        long dima0_sort=z->get_range(h2b)*z->get_range(q5b)*z->get_range(h4b)*z->get_range(p6b); 
        long dima0=dim_common*dima0_sort; 
        if (dima0>0L) { 
         double* k_a0_sort=z->mem()->malloc_local_double(dima0); 
         double* k_a0=z->mem()->malloc_local_double(dima0); 
         z->v2()->get_block(p6b_0+(z->nab())*(h4b_0+(z->nab())*(q5b_0+(z->nab())*(h2b_0))),k_a0); 
         z->sort_indices4(k_a0,k_a0_sort,z->get_range(h2b),z->get_range(q5b),z->get_range(h4b),z->get_range(p6b),0,1,2,3,+1.0,false); 
         z->mem()->free_local_double(k_a0); 
         double* k_c=z->mem()->malloc_local_double(dimc); 
         z->sort_indices4(k_a0_sort,k_c,z->get_range(h2b),z->get_range(q5b),z->get_range(h4b),z->get_range(p6b),0,1,2,3,+1.0,false); 
         in[3]->add_block(p6b-z->noab()+z->nvab()*(h4b+z->noab()*(q5b-z->noab()-z->nvab()+z->ncab()*(h2b))),k_c); 
         z->mem()->free_local_double(k_c); 
         z->mem()->free_local_double(k_a0_sort); 
        } 
       } 
      } 
     } 
    } 
   } 
  } 
 } 
} 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::offset_smith_2_7(){ 
 
long size=0L; 
for (long h2b=0L;h2b<z->noab();++h2b) { 
 for (long q5b=z->noab()+z->nvab();q5b<z->nab();++q5b) { 
  for (long h4b=0L;h4b<z->noab();++h4b) { 
   for (long p6b=z->noab();p6b<z->noab()+z->nvab();++p6b) { 
    if (z->get_spin(h2b)+z->get_spin(q5b)==z->get_spin(h4b)+z->get_spin(p6b)) { 
     if ((z->get_sym(h2b)^(z->get_sym(q5b)^(z->get_sym(h4b)^z->get_sym(p6b))))==(z->irrep_t()^z->irrep_v())) { 
      if (!z->restricted() || z->get_spin(h2b)+z->get_spin(q5b)+z->get_spin(h4b)+z->get_spin(p6b)!=8L) { 
       in[3]->input_offset(p6b-z->noab()+z->nvab()*(h4b+z->noab()*(q5b-z->noab()-z->nvab()+z->ncab()*(h2b))),size); 
       size+=z->get_range(h2b)*z->get_range(q5b)*z->get_range(h4b)*z->get_range(p6b); 
      } 
     } 
    } 
   } 
  } 
 } 
} 
in[3]->set_filesize(size); 
in[3]->createfile(); 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::smith_2_8(){ 
      
for (long h2b=0L;h2b<z->noab();++h2b) { 
 for (long p5b=z->noab();p5b<z->noab()+z->nvab();++p5b) { 
  for (long h3b=0L;h3b<z->noab();++h3b) { 
   for (long h4b=h3b;h4b<z->noab();++h4b) { 
    long tileoffset; 
    tileoffset=(h4b+z->noab()*(h3b+z->noab()*(p5b-z->noab()+z->nvab()*(h2b)))); 
    if (in[2]->is_this_local(tileoffset)) { 
     if (!z->restricted() || z->get_spin(h2b)+z->get_spin(p5b)+z->get_spin(h3b)+z->get_spin(h4b)!=8L) { 
      if (z->get_spin(h2b)+z->get_spin(p5b)==z->get_spin(h3b)+z->get_spin(h4b)) { 
       if ((z->get_sym(h2b)^(z->get_sym(p5b)^(z->get_sym(h3b)^z->get_sym(h4b))))==(z->irrep_t()^z->irrep_y())) { 
        long dimc=z->get_range(h2b)*z->get_range(p5b)*z->get_range(h3b)*z->get_range(h4b); 
        double* k_c_sort=z->mem()->malloc_local_double(dimc); 
        std::fill(k_c_sort,k_c_sort+(size_t)dimc,0.0); 
        for (long h6b=0L;h6b<z->noab();++h6b) { 
         if (z->get_spin(p5b)==z->get_spin(h6b)) { 
          if ((z->get_sym(p5b)^z->get_sym(h6b))==z->irrep_t()) { 
           long p5b_0,h6b_0; 
           z->restricted_2(p5b,h6b,p5b_0,h6b_0); 
           long h2b_1,h6b_1,h3b_1,h4b_1; 
           z->restricted_4(h2b,h6b,h3b,h4b,h2b_1,h6b_1,h3b_1,h4b_1); 
           long dim_common=z->get_range(h6b); 
           long dima0_sort=z->get_range(p5b); 
           long dima0=dim_common*dima0_sort; 
           long dima1_sort=z->get_range(h2b)*z->get_range(h3b)*z->get_range(h4b); 
           long dima1=dim_common*dima1_sort; 
           if (dima0>0L && dima1>0L) { 
            double* k_a0_sort=z->mem()->malloc_local_double(dima0); 
            double* k_a0=z->mem()->malloc_local_double(dima0); 
            z->t1()->get_block(h6b_0+z->noab()*(p5b_0-z->noab()),k_a0); 
            z->sort_indices2(k_a0,k_a0_sort,z->get_range(p5b),z->get_range(h6b),0,1,+1.0,false); 
            z->mem()->free_local_double(k_a0); 
            double* k_a1_sort=z->mem()->malloc_local_double(dima1); 
            double* k_a1=z->mem()->malloc_local_double(dima1); 
            if (h2b<h6b) { 
             z->glambda2()->get_block(h4b_1+z->noab()*(h3b_1+z->noab()*(h6b_1+z->noab()*(h2b_1))),k_a1); 
             z->sort_indices4(k_a1,k_a1_sort,z->get_range(h2b),z->get_range(h6b),z->get_range(h3b),z->get_range(h4b),3,2,0,1,+1.0,false); 
            } 
            else if (h6b<=h2b) { 
             z->glambda2()->get_block(h4b_1+z->noab()*(h3b_1+z->noab()*(h2b_1+z->noab()*(h6b_1))),k_a1); 
             z->sort_indices4(k_a1,k_a1_sort,z->get_range(h6b),z->get_range(h2b),z->get_range(h3b),z->get_range(h4b),3,2,1,0,-1.0,false); 
            } 
            z->mem()->free_local_double(k_a1); 
            double factor=1.0; 
            z->smith_dgemm(dima0_sort,dima1_sort,dim_common,factor,k_a0_sort,dim_common,k_a1_sort,dim_common,1.0,k_c_sort,dima0_sort); 
            z->mem()->free_local_double(k_a1_sort); 
            z->mem()->free_local_double(k_a0_sort); 
           } 
          } 
         } 
        } 
        double* k_c=z->mem()->malloc_local_double(dimc); 
        z->sort_indices4(k_c_sort,k_c,z->get_range(h4b),z->get_range(h3b),z->get_range(h2b),z->get_range(p5b),2,3,1,0,+0.5,false); 
        in[2]->add_block(h4b+z->noab()*(h3b+z->noab()*(p5b-z->noab()+z->nvab()*(h2b))),k_c); 
        z->mem()->free_local_double(k_c); 
        z->mem()->free_local_double(k_c_sort); 
       } 
      } 
     } 
    } 
   } 
  } 
 } 
} 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::smith_3_11(){ 
      
for (long h2b=0L;h2b<z->noab();++h2b) { 
 for (long q5b=z->noab()+z->nvab();q5b<z->nab();++q5b) { 
  for (long h4b=0L;h4b<z->noab();++h4b) { 
   for (long p6b=z->noab();p6b<z->noab()+z->nvab();++p6b) { 
    long tileoffset; 
    tileoffset=(p6b-z->noab()+z->nvab()*(h4b+z->noab()*(q5b-z->noab()-z->nvab()+z->ncab()*(h2b)))); 
    if (in[3]->is_this_local(tileoffset)) { 
     if (!z->restricted() || z->get_spin(h2b)+z->get_spin(q5b)+z->get_spin(h4b)+z->get_spin(p6b)!=8L) { 
      if (z->get_spin(h2b)+z->get_spin(q5b)==z->get_spin(h4b)+z->get_spin(p6b)) { 
       if ((z->get_sym(h2b)^(z->get_sym(q5b)^(z->get_sym(h4b)^z->get_sym(p6b))))==(z->irrep_t()^z->irrep_v())) { 
        long dimc=z->get_range(h2b)*z->get_range(q5b)*z->get_range(h4b)*z->get_range(p6b); 
        double* k_c_sort=z->mem()->malloc_local_double(dimc); 
        std::fill(k_c_sort,k_c_sort+(size_t)dimc,0.0); 
        for (long p7b=z->noab();p7b<z->noab()+z->nvab();++p7b) { 
         if (z->get_spin(p7b)==z->get_spin(h4b)) { 
          if ((z->get_sym(p7b)^z->get_sym(h4b))==z->irrep_t()) { 
           long p7b_0,h4b_0; 
           z->restricted_2(p7b,h4b,p7b_0,h4b_0); 
           long h2b_1,q5b_1,p6b_1,p7b_1; 
           z->restricted_4(h2b,q5b,p6b,p7b,h2b_1,q5b_1,p6b_1,p7b_1); 
           long dim_common=z->get_range(p7b); 
           long dima0_sort=z->get_range(h4b); 
           long dima0=dim_common*dima0_sort; 
           long dima1_sort=z->get_range(h2b)*z->get_range(q5b)*z->get_range(p6b); 
           long dima1=dim_common*dima1_sort; 
           if (dima0>0L && dima1>0L) { 
            double* k_a0_sort=z->mem()->malloc_local_double(dima0); 
            double* k_a0=z->mem()->malloc_local_double(dima0); 
            z->t1()->get_block(h4b_0+z->noab()*(p7b_0-z->noab()),k_a0); 
            z->sort_indices2(k_a0,k_a0_sort,z->get_range(p7b),z->get_range(h4b),1,0,+1.0,false); 
            z->mem()->free_local_double(k_a0); 
            double* k_a1_sort=z->mem()->malloc_local_double(dima1); 
            double* k_a1=z->mem()->malloc_local_double(dima1); 
            if (p6b<p7b) { 
             z->v2()->get_block(p7b_1+(z->nab())*(p6b_1+(z->nab())*(q5b_1+(z->nab())*(h2b_1))),k_a1); 
             z->sort_indices4(k_a1,k_a1_sort,z->get_range(h2b),z->get_range(q5b),z->get_range(p6b),z->get_range(p7b),2,1,0,3,+1.0,false); 
            } 
            else if (p7b<=p6b) { 
             z->v2()->get_block(p6b_1+(z->nab())*(p7b_1+(z->nab())*(q5b_1+(z->nab())*(h2b_1))),k_a1); 
             z->sort_indices4(k_a1,k_a1_sort,z->get_range(h2b),z->get_range(q5b),z->get_range(p7b),z->get_range(p6b),3,1,0,2,-1.0,false); 
            } 
            z->mem()->free_local_double(k_a1); 
            double factor=1.0; 
            z->smith_dgemm(dima0_sort,dima1_sort,dim_common,factor,k_a0_sort,dim_common,k_a1_sort,dim_common,1.0,k_c_sort,dima0_sort); 
            z->mem()->free_local_double(k_a1_sort); 
            z->mem()->free_local_double(k_a0_sort); 
           } 
          } 
         } 
        } 
        double* k_c=z->mem()->malloc_local_double(dimc); 
        z->sort_indices4(k_c_sort,k_c,z->get_range(p6b),z->get_range(q5b),z->get_range(h2b),z->get_range(h4b),2,1,3,0,-0.5,false); 
        in[3]->add_block(p6b-z->noab()+z->nvab()*(h4b+z->noab()*(q5b-z->noab()-z->nvab()+z->ncab()*(h2b))),k_c); 
        z->mem()->free_local_double(k_c); 
        z->mem()->free_local_double(k_c_sort); 
       } 
      } 
     } 
    } 
   } 
  } 
 } 
} 
z->mem()->sync(); 
} 
  
void LAMBDAPENERGY::smith_k0(){ 
      
for (long p4b=z->noab();p4b<z->noab()+z->nvab();++p4b) { 
 for (long q3b=z->noab()+z->nvab();q3b<z->nab();++q3b) { 
  long tileoffset; 
  tileoffset=(q3b-z->noab()-z->nvab()+z->ncab()*(p4b-z->noab())); 
  if (kn[0]->is_this_local(tileoffset)) { 
   if (!z->restricted() || z->get_spin(p4b)+z->get_spin(q3b)!=4L) { 
    if (z->get_spin(p4b)==z->get_spin(q3b)) { 
     if ((z->get_sym(p4b)^z->get_sym(q3b))==(z->irrep_t()^z->irrep_y())) { 
      long dimc=z->get_range(p4b)*z->get_range(q3b); 
      double* k_c_sort=z->mem()->malloc_local_double(dimc); 
      std::fill(k_c_sort,k_c_sort+(size_t)dimc,0.0); 
      for (long h6b=0L;h6b<z->noab();++h6b) { 
       for (long h7b=h6b;h7b<z->noab();++h7b) { 
        for (long p5b=z->noab();p5b<z->noab()+z->nvab();++p5b) { 
         if (z->get_spin(p4b)+z->get_spin(p5b)==z->get_spin(h6b)+z->get_spin(h7b)) { 
          if ((z->get_sym(p4b)^(z->get_sym(p5b)^(z->get_sym(h6b)^z->get_sym(h7b))))==z->irrep_t()) { 
           long p4b_0,p5b_0,h6b_0,h7b_0; 
           z->restricted_4(p4b,p5b,h6b,h7b,p4b_0,p5b_0,h6b_0,h7b_0); 
           long h6b_1,h7b_1,p5b_1,q3b_1; 
           z->restricted_4(h6b,h7b,p5b,q3b,h6b_1,h7b_1,p5b_1,q3b_1); 
           long dim_common=z->get_range(h6b)*z->get_range(h7b)*z->get_range(p5b); 
           long dima0_sort=z->get_range(p4b); 
           long dima0=dim_common*dima0_sort; 
           long dima1_sort=z->get_range(q3b); 
           long dima1=dim_common*dima1_sort; 
           if (dima0>0L && dima1>0L) { 
            double* k_a0_sort=z->mem()->malloc_local_double(dima0); 
            double* k_a0=z->mem()->malloc_local_double(dima0); 
            if (p4b<p5b) { 
             z->t2()->get_block(h7b_0+z->noab()*(h6b_0+z->noab()*(p5b_0-z->noab()+z->nvab()*(p4b_0-z->noab()))),k_a0); 
             z->sort_indices4(k_a0,k_a0_sort,z->get_range(p4b),z->get_range(p5b),z->get_range(h6b),z->get_range(h7b),0,1,3,2,+1.0,false); 
            } 
            else if (p5b<=p4b) { 
             z->t2()->get_block(h7b_0+z->noab()*(h6b_0+z->noab()*(p4b_0-z->noab()+z->nvab()*(p5b_0-z->noab()))),k_a0); 
             z->sort_indices4(k_a0,k_a0_sort,z->get_range(p5b),z->get_range(p4b),z->get_range(h6b),z->get_range(h7b),1,0,3,2,-1.0,false); 
            } 
            z->mem()->free_local_double(k_a0); 
            double* k_a1_sort=z->mem()->malloc_local_double(dima1); 
            double* k_a1=z->mem()->malloc_local_double(dima1); 
            z->ly()->get_block(q3b_1-z->noab()-z->nvab()+z->ncab()*(p5b_1-z->noab()+z->nvab()*(h7b_1+z->noab()*(h6b_1))),k_a1); 
            z->sort_indices4(k_a1,k_a1_sort,z->get_range(h6b),z->get_range(h7b),z->get_range(p5b),z->get_range(q3b),3,2,1,0,+1.0,false); 
            z->mem()->free_local_double(k_a1); 
            double factor=1.0; 
            if (h6b==h7b) { 
             factor=factor/2.0; 
            } 
            z->smith_dgemm(dima0_sort,dima1_sort,dim_common,factor,k_a0_sort,dim_common,k_a1_sort,dim_common,1.0,k_c_sort,dima0_sort); 
            z->mem()->free_local_double(k_a1_sort); 
            z->mem()->free_local_double(k_a0_sort); 
           } 
          } 
         } 
        } 
       } 
      } 
      double* k_c=z->mem()->malloc_local_double(dimc); 
      z->sort_indices2(k_c_sort,k_c,z->get_range(q3b),z->get_range(p4b),1,0,+0.5/0.5,false); 
      kn[0]->add_block(q3b-z->noab()-z->nvab()+z->ncab()*(p4b-z->noab()),k_c); 
      z->mem()->free_local_double(k_c); 
      z->mem()->free_local_double(k_c_sort); 
     } 
    } 
   } 
  } 
 } 
} 
z->mem()->sync(); 
} 

