
molecule = $:water

basis<SymmGaussianBasisSet>: (
  molecule = $:molecule
  %name = "STO-3G"
  %name = "6-31G"
  %name = "DZ (Dunning)"
  %name = "6-31G*"
  %name = "6-31G**"
  %name = "DZP (Dunning)"
  %name = "cc-pVDZ"
  %name = "cc-pVTZ"
  %name = "cc-pVQZ"
  %name = "aug-cc-pVDZ"
  %name = "aug-cc-pVTZ"
  name = "aug-cc-pVQZ"
)

water<Molecule>: (
  symmetry = c2v
  { atoms geometry } = {
      o    [   0.0  0.0   0.0 ]
      o    [   1.5  0.0   1.0 ]
  }
)

sodium<Molecule>: (
  { atoms geometry } = { Na [ 0 0 0 ] }
)

