TOPDIR=../../..
ifndef SRCDIR
  SRCDIR=.
endif

include $(SRCDIR)/$(TOPDIR)/lib/GlobalMakefile

SUBDIRS = options sgen ref container misc class keyval state group render

include $(SRCDIR)/$(TOPDIR)/lib/GlobalSubDirs

