TOPDIR=../../..
ifndef SRCDIR
  SRCDIR=.
endif

include $(SRCDIR)/$(TOPDIR)/lib/GlobalMakefile

SUBDIRS = options ref container class state misc keyval group render

include $(SRCDIR)/$(TOPDIR)/lib/GlobalSubDirs

