TOPDIR=../..
ifndef SRCDIR
  SRCDIR=.
endif

include $(SRCDIR)/$(TOPDIR)/lib/GlobalMakefile

SUBDIRS = options sgen container misc class keyval unix state group

include $(SRCDIR)/$(TOPDIR)/lib/GlobalSubDirs

