TOPDIR=../../..
ifndef SRCDIR
  SRCDIR=$(shell pwd)
endif

include $(SRCDIR)/$(TOPDIR)/lib/GlobalMakefile

SUBDIRS = scmat mmisc optimize isosurf symmetry distarray4

include $(SRCDIR)/$(TOPDIR)/lib/GlobalSubDirs

