TOPDIR=../../..
ifndef SRCDIR
  SRCDIR=$(shell pwd)
endif

include $(SRCDIR)/$(TOPDIR)/lib/GlobalMakefile

SUBDIRS = options ref container class keyval state misc group render

include $(SRCDIR)/$(TOPDIR)/lib/GlobalSubDirs

