
 /* Global data for the ip routines. */
/* $Log$
 * Revision 1.1  1993/12/29 12:53:56  etseidl
 * Initial revision
 *
 * Revision 1.2  1992/03/30  23:08:00  seidl
 * merge in sandia changes
 *
 * Revision 1.4  91/12/02  17:38:41  cljanss
 * cannot use names input and output in the scanner due to the macro names
 * generated by the scanner generator
 * 
 * Revision 1.3  91/11/18  17:23:00  cljanss
 * define FILENAME_MAX in case it is not already defined in the system files
 * 
 * Revision 1.2  91/07/19  14:42:33  cljanss
 * Changed the way that generation modules are selected.
 * 
 * Revision 1.1  1991/06/15  21:15:38  janssen
 * Initial revision
 * */

#ifndef FILENAME_MAX
#define FILENAME_MAX 256
#endif

#ifdef _ALLOCATE_GLOBAL_
#define EXTERN
#define INITIALIZE(x,y) x=y
#define VECTOR(x,y) x[y]
#else
#define EXTERN extern
#define INITIALIZE(x,y) x
/* AIXV3 chokes with this: #define VECTOR(x,y) *x */
#define VECTOR(x,y) x[y]
#endif

EXTERN char * progname;

#ifndef IN_SCANNER
EXTERN FILE *input;
EXTERN FILE *output;
#endif

/* Since LEX def's output, I need another name for the output file
 * that is used by the scanner: */
EXTERN FILE *includeoutput;
EXTERN declaration_t INITIALIZE(*dl,NULL);
EXTERN char VECTOR(BaseName,FILENAME_MAX);
EXTERN name_list_t INITIALIZE(*default_modules,NULL);

extern FILE *yyin;

