TOPDIR=../../..
ifndef SRCDIR
  SRCDIR=.
endif

include $(SRCDIR)/$(TOPDIR)/lib/GlobalMakefile

SUBDIRS = array linpackd dmt scmat optimize topology isosurf symmetry

include $(SRCDIR)/$(TOPDIR)/lib/GlobalSubDirs

