TOPDIR=../../..
ifndef SRCDIR
  SRCDIR=$(shell pwd)
endif

include $(SRCDIR)/$(TOPDIR)/lib/GlobalMakefile

SUBDIRS = linpackd scmat optimize topology isosurf symmetry

include $(SRCDIR)/$(TOPDIR)/lib/GlobalSubDirs

