@c -*-texinfo-*-
@node The State Library, The SavableState Class, , Top
@chapter The State Library
@cindex State Library

The state library provide means for objects to save and restore their
state.

@menu
* The SavableState Class:: The abstract base for savable/restorable classes.
* The StateIn Class:: The abstract base class for state restoration.
* The StateInFile Class:: The classes for restoring from files.
* The StateOut Class:: The abstract base class for saving state.
* The StateOutFile Class:: The classes for saving to files.
* The StateIn/Out Network Classes:: Saving/restoring across the net.
@end menu

@include src.lib/util/state/savable.texi
@include src.lib/util/state/sin.texi
@include src.lib/util/state/sinfile.texi
@include src.lib/util/state/sout.texi
@include src.lib/util/state/soutfile.texi
@include src.lib/util/state/net.texi
